README.md
Also, the branch protection rule worked and I had to do this via PR 🎉
=> Update some developer docs.

package-lock.json, package.json, public/index.html, src/web/fonts.scss, src/web/index.scss
As far as I can tell, this kind of usage is valid under terms of the OFL - we're just using the provided distributions.
=> Include Inter and Roboto Mono fonts.

src/web/components/Core/Dialog.stories.tsx, src/web/components/Core/Dialog.tsx, src/web/screens/addTeamMemberDialog.tsx
Switch Dialog component to take JSX as a trigger instead of just text.
=> Switch Dialog to take JSX as a trigger instead of just text

src/web/components/Core/Form.spec.tsx, src/web/components/Core/Form.stories.tsx, src/web/components/Input/CheckboxInput.stories.tsx, src/web/components/Input/CheckboxInput.tsx, src/web/components/Input/SelectInput.tsx
1. This PR addresses an issue with default values not being displayed in Select and CheckBox. With this update, default values will be correctly displayed in both components. Additionally, unit test has been added to ensure that default values are displayed as expected.
2. In this PR, I also extended the functionality of the CheckBox component to support capturing boolean values.
=> Fix checkbox and select default values

.github/workflows/docker-publish-api-migrations.yaml, Dockerfile_ssportal_migration
Creating a docker container that will run as a migration job, before the deployment of pod.
This will be published via github actions, similar to other container images.
=> kba-uid-1073 add database migration docker container

.github/workflows/sync-sendgripd-template.yaml, emailTemplates/newParticipantReadyForReview.hbs, src/api/envars.ts, src/api/participantsRouter.ts, src/api/services/emailService.ts, src/api/services/participantsService.ts
=> TAM email template 

src/web/components/Core/Dialog.scss, src/web/components/Core/Dialog.tsx, src/web/screens/dashboard.tsx, src/web/screens/searchAndAddParticipantsDialog.scss, src/web/screens/searchAndAddParticipantsDialog.tsx, src/web/screens/sharingPermissions.tsx
This PR is for  new sharing permission workflow which is built up using [the search bar components](https://github.com/IABTechLab/uid2-self-serve-portal/pull/47) and [participants table component](https://github.com/IABTechLab/uid2-self-serve-portal/pull/48)
Add participants workflow
https://github.com/IABTechLab/uid2-self-serve-portal/assets/116539741/97152c8d-c90f-4b8c-bd74-d5e86feaa5c0
=> Build the sharing permission page

src/web/App.scss, src/web/components/Core/Banner.scss, src/web/components/Core/Banner.spec.tsx, src/web/components/Core/Banner.stories.tsx, src/web/components/Core/Banner.tsx, src/web/components/Core/Dialog.scss, src/web/components/Core/Dialog.stories.tsx, src/web/components/Core/TermsAndConditionsDialog.scss, src/web/components/Core/TermsAndConditionsDialog.stories.tsx, src/web/components/Core/TermsAndConditionsDialog.tsx, src/web/components/Input/SelectInput.tsx, src/web/screens/addTeamMemberDialog.scss, src/web/screens/addTeamMemberDialog.tsx, src/web/styles/buttons.scss, src/web/styles/themes.scss
=> Confirmation dialog and banner

src/web/components/Core/Tooltip.tsx, src/web/components/SharingPermission/ParticipantSearchBar.scss, src/web/components/SharingPermission/ParticipantSearchBar.tsx, src/web/components/SharingPermission/ParticipantsTable.tsx, src/web/components/SharingPermission/SharingPermissionsTable.scss, src/web/components/SharingPermission/SharingPermissionsTable.tsx, src/web/components/SharingPermission/searchAndAddParticipantsDialog.scss, src/web/components/SharingPermission/searchAndAddParticipantsDialog.tsx, src/web/screens/sharingPermissions.scss, src/web/screens/sharingPermissions.tsx, src/web/styles/buttons.scss, src/web/styles/text.scss, src/web/styles/themes.scss
- Fix the form is submitted when clicking tooltip
- Fix the font-size and title of sharing permission table
- Update the style of the disabled button
- Add outlines for search bar
- Remove display of `0 participant` when no participant is selected and captialize the P in `Participants` 
- Hide placeholder when search bar clicked
- Remove "Participant Not Appearing in Search?
- Hide checkbox in the table header when participant is shared
- Fix styling of delete permission popup
=> UID2-1348 fix click on tooltip cause error and sharing permission page

src/web/components/Core/Dialog.scss, src/web/components/Core/Dialog.tsx, src/web/screens/addTeamMemberDialog.scss, src/web/screens/addTeamMemberDialog.tsx, src/web/screens/sharingPermissions.scss, src/web/styles/buttons.scss
=> Remove checkbox and fix the dialog size on large screen

README.md
Add Setting up UI Dev Environment, fix some typos and add missing `npm install`
=> ajy-UID2-1423-Update-readme-for-UI-dev

.eslintrc.js, src/api/entities/Participant.ts, src/api/participantsRouter.ts, src/web/components/Core/Dialog.tsx, src/web/components/Input/FormError.stories.tsx, src/web/components/Input/FormError.tsx, src/web/components/Input/StyledCheckbox.stories.tsx, src/web/components/Input/StyledCheckbox.tsx, src/web/services/participant.ts
Remove status from the participant creation endpoint. Make triggerButton optional for dialogs.
Add FormError and StyledCheckbox components.
=> Remove a lint rule that wasn't adding anything good.

src/api/services/adminServiceClient.ts, src/api/services/participantsService.ts
According to this Admin service's change - [PR](https://github.com/IABTechLab/uid2-admin/pull/85/)
Update admin endpoints
Tests
https://github.com/IABTechLab/uid2-self-serve-portal/assets/116539741/68a5b6a5-e5ca-4507-9366-523eb318427e
=> Update admin endpoint

src/api/configureApi.ts, src/web/components/Home/SharingPermissionCard.stories.tsx, src/web/components/Home/SharingPermissionCard.tsx, src/web/screens/home.tsx
- Fix backend return 500 when the access token is invalid
- Fix home page send request before token is refreshed
=> UID2-1458 Fix home page error when first login

README.md
Add a reference to generating a SSP_KK_SECRET in the Setting up UI Dev Environment section. And minor changes like adding a new heading and clarifying some steps.
=> ajy-UID2-1515-Update-readme-UI-dev-section

src/web/contexts/ParticipantProvider.tsx, src/web/services/participant.ts
Move from ParticipantResponse to ParticipantDTO, for consistency.
=> ajy-UID2-1443-Move-off-ParticipantResponse-type

package-lock.json, package.json, src/web/components/Core/Collapsible.scss, src/web/components/Core/Collapsible.stories.tsx, src/web/components/Core/Collapsible.tsx
Add collapsible component from Radix
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/09eb0f20-1660-4aee-a2f7-64d0a4cf1c74
=> ajy-UID2-1443-Collapsible-component

src/web/components/Core/Collapsible.scss, src/web/components/ParticipantRequests/ParticipantRequestsTable.scss, src/web/components/ParticipantRequests/ParticipantRequestsTable.stories.tsx, src/web/components/SharingPermission/BulkAddPermissions.scss, src/web/components/SharingPermission/ParticipantItem.scss, src/web/components/SharingPermission/ParticipantSearchBar.scss, src/web/components/SharingPermission/ParticipantsTable.scss, src/web/components/SharingPermission/SharingPermissionsTable.scss, src/web/components/SharingPermission/SharingPermissionsTable.stories.tsx, src/web/styles/tables.scss, src/web/styles/text.scss, src/web/styles/themes.scss
Affected areas include:
- Participant tables
- ParticipantRequestsTable (in Managing Participants)
- h2 (trimmed 10px)
**Participant table**
Before
After
**Participant table empty**
Before
After
**Participant request table**
Before
After
**Other changes**
- Added storybook for participants request table.
=> ajy-UID2-1537-Implement-styling-changes

src/web/components/BusinessContacts/BusinessContact.tsx, src/web/components/BusinessContacts/BusinessContactsTable.tsx
**Email Contacts Screen**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/e7990f8a-b1e6-4eaa-b2c1-9c33701e527c
**Storybook**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/ed07a352-ddea-4e27-8798-987dc336634e
=> ajy-UID2-1561-Add-confirmation-when-deleting-email-contact

src/web/App.tsx, src/web/components/Core/PortalHeader.scss, src/web/components/Core/PortalHeader.stories.tsx, src/web/components/Core/PortalHeader.tsx, src/web/screens/dashboard.scss, src/web/styles/buttons.scss, src/web/styles/text.scss, src/web/styles/themes.scss
**Adjust spacing**
**Cursor pointer**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/fe711b4d-4a84-411d-99b5-46eddda63e55
**Disabled cursor**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/6ed083e3-f6d3-49a0-8501-ab4309c05dce
=> ajy-UID2-1563-Implement-feedback-regarding-styling

keycloak/realm/realm-export.json, src/api/middleware/approversMiddleware.ts, src/api/participantsRouter.ts, src/api/services/approversService.ts, src/api/services/participantsService.ts, src/api/services/usersService.ts, src/api/tests/approversMiddleware.spec.ts, src/api/tests/participantsService.spec.ts, src/api/tests/queryMocks.ts
1. Add new endpoint to update status of participant, take the change of participant name and type if any
2. Add middleware to check if current user is approver and if user has permission to approve current participant type
3. Add unit tests
=> UID2-1029 approve participant endpoint

src/web/components/Core/Dialog.scss, src/web/components/SharingPermission/SearchAndAddParticipants.tsx, src/web/styles/text.scss
**List participants in add dialog + copy**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/6b588b5b-e4c4-40a2-8a3d-49ac4ff43f70
**Gap styling**
Before
After
**Line height styling**
Before
After
=> ajy-UID2-1564-List-participants-in-add-dialog

src/web/screens/accountPending.tsx, src/web/screens/dashboard.tsx, src/web/screens/sharingPermissions.tsx
**Account pending**
**Terms and conditions on dashboard**
**Sharing permissions**
=> ajy-UID2-1565-Implement-various-copy-changes

emailTemplates/accountHasBeenConfirmed.hbs, emailTemplates/newParticipantReadyForReview.hbs, src/api/entities/User.ts, src/api/participantsRouter.ts, src/api/services/participantsService.ts
- Run Sendgrid sync
- Add a new email template for participant approved
- Remove button from `new participant ready for review` template
- Fix the font in both email templates
- Send email when account is approved
=> jyg-UID2-1578 Add account has been confirmed email

src/api/entities/AuditTrail.ts, src/api/entities/Participant.ts, src/api/participantsRouter.ts, src/api/services/auditTrailService.ts, src/api/services/participantsService.ts
=> UID2-1029 Create audit trail when account is approved

package.json, src/database/migrations/20230803014224_CreateAuditTrailsTableAndMigrateData.ts
=> Copy types into migration.

package-lock.json, package.json, src/api/configureApi.ts, src/api/routers/sitesRouter.ts, src/api/services/adminServiceClient.ts, src/web/components/Core/SideNav.tsx, src/web/components/ParticipantRequests/ParticipantApprovalForm.scss, src/web/components/ParticipantRequests/ParticipantApprovalForm.tsx, src/web/components/ParticipantRequests/ParticipantRequestForm.stories.tsx, src/web/components/ParticipantRequests/ParticipantRequestItem.tsx, src/web/components/ParticipantRequests/ParticipantRequestsTable.tsx, src/web/screens/manageParticipants.tsx, src/web/services/SwrHelpers.tsx, src/web/services/participant.ts, src/web/services/site.ts
Introduce a sites router.
Add an admin client call to fetch the sites list.
Fix a react error when rendering the nav.
Remove the Participant Approval Form from the dialog so it can be used without a dialog. Add a storybook story for the participant approval form.
=> Add SWR for data fetching and add some helpers.

src/web/components/Search/SearchBar.tsx, src/web/components/SharingPermission/ParticipantSearchBar.tsx, src/web/components/SharingPermission/SearchAndAddParticipants.tsx
- Don't automatically close results when selecting a participant
- Close results onBlur (i.e. when clicking outside of the control)
- Always show the "add" button
**Before**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/14b9e4a7-7f99-4901-8853-75cc210181aa
**After**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/d346699e-0bfb-442b-ba09-b5a84c33a63f
=> ajy-UID2-1596-Improve-search-and-add-workflow

src/web/components/SharingPermission/ParticipantsTable.stories.tsx, src/web/components/SharingPermission/ParticipantsTable.tsx, src/web/components/SharingPermission/SharingPermissionsTable.scss, src/web/components/SharingPermission/SharingPermissionsTable.spec.tsx, src/web/components/SharingPermission/SharingPermissionsTable.tsx
https://github.com/IABTechLab/uid2-self-serve-portal/assets/116539741/a4b16896-0308-4ed9-8eaf-421d9a350203
=> jyg-UID2-1475 Took out selectAllCheckbox from table header

.env, package-lock.json, package.json, src/web/components/Core/MultiSelectDropdown.scss, src/web/components/Core/MultiSelectDropdown.stories.tsx, src/web/components/Core/MultiSelectDropdown.tsx
https://github.com/IABTechLab/uid2-self-serve-portal/assets/116539741/89fc0911-d303-409c-98f7-d332cc30953c
=> jyg-UID2-1475 Multi select dropdown filter

package-lock.json, src/web/components/Core/MultiSelectDropdown.scss, src/web/components/SharingPermission/SharingPermissionsTable.stories.tsx, src/web/components/SharingPermission/SharingPermissionsTable.tsx, src/web/screens/sharingPermissions.tsx, src/web/utils/errorHandler.scss
https://github.com/IABTechLab/uid2-self-serve-portal/assets/116539741/4e086fc3-def2-40ac-a9ed-af0b15d4eaf7
=> jyg-UID2-1475 Apply type filter to sharing permission table

src/web/components/Core/MultiSelectDropdown.scss, src/web/components/Core/MultiSelectDropdown.tsx
=> To make the dropdown not matching the triggers length

src/api/helpers/siteConvertingHelpers.ts, src/api/services/adminServiceHelpers.ts, src/api/tests/siteConvertingHelpers.spec.ts, src/web/components/ParticipantRequests/ParticipantApprovalForm.spec.tsx, src/web/components/ParticipantRequests/ParticipantRequestForm.stories.tsx
- Update`types` in siteDTO to `clientTypes`
- Make `clientTypes` optional
=> jyg-UID2-1745 fix broken admin service calls

src/web/components/SharingPermission/ParticipantSearchBar.tsx, src/web/components/SharingPermission/TypeFilter.stories.tsx, src/web/components/SharingPermission/TypeFilter.tsx
=> selection bug fix

src/web/components/BusinessContacts/BusinessContact.tsx, src/web/components/BusinessContacts/BusinessContactsTable.scss, src/web/components/Core/StatusPopup.scss, src/web/components/Core/StatusPopup.tsx, src/web/components/TeamMember/TeamMember.tsx, src/web/components/TeamMember/TeamMembersTable.scss, src/web/screens/emailContacts.tsx, src/web/screens/teamMembers.tsx, src/web/services/participant.ts, src/web/services/userAccount.ts
Add action confirmations via StatusPopup.
=> confirmations work

src/api/routers/participantsRouter.ts
This uses the approach recommended by the Objection js [docs](https://vincit.github.io/objection.js/guide/query-examples.html#update-queries)
**Manual test on local**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/a84b3eca-9343-49c9-b8f4-2fa696e94fbe
=> ajy-UID2-Fix-completedRecommendations-workflow

src/api/configureApi.ts, src/api/routers/businessContactsRouter.ts, src/web/screens/emailContacts.tsx, src/web/screens/teamMembers.tsx, src/web/services/userAccount.ts
Correctly return 404 on incorrect routes and use status rather than statusText.
=> Sas UI d2 1862 api status code bug2

src/api/entities/User.ts, src/api/routers/usersRouter.ts, src/api/services/participantsService.ts, src/api/services/usersService.ts, src/database/migrations/20230912185913_AddDeletedFlagToUsersTable.ts
We have a foreign key relationship from the auditTrails table to users.  This prevents us from deleting a user that has anything on auditTrails.  So rather than deleting, we will remove the participant relationship and add some randomization to the email address to prevent future duplication.
=> Sas UI d2 1793 delete user with audit trail

src/web/components/SharingPermission/SharingPermissionsTable.tsx
=> ajy-UID2-Use-type-descriptions-in-delete-dialog

DeploymentSteps.md, keycloak/realm/realm-export.json, public/index.html, src/web/components/SharingPermission/ParticipantItem.tsx
- Remove logo from paritcipant lists
- Update tab name
=> Jyg remove logo from participant list

src/web/components/SharingPermission/BulkAddPermissions.tsx, src/web/components/SharingPermission/bulkAddPermissionsHelpers.ts
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/c2ae17dd-8e3b-43b1-aab2-b0e0f3e339a4
=> ajy-UID2-1937-Disable-bulk-add-btn-when-no-changes

src/api/services/adminServiceClient.ts, src/web/components/KeyPairs/KeyPair.stories.tsx, src/web/components/KeyPairs/KeyPair.tsx, src/web/components/KeyPairs/KeyPairsTable.stories.tsx, src/web/screens/keyPairsScreen.tsx
Add name field to client side keypairs
=> name on keypairs

src/api/entities/AuditTrail.ts, src/api/routers/participantsRouter.ts, src/api/services/auditTrailService.ts, src/api/services/participantsService.ts, src/web/screens/sharingPermissions.tsx, src/web/services/participant.ts
Decouple update sharing types from addSharingParticipants endpoint
=> Decouple update sharing type

src/web/components/Home/SharingPermissionCard.tsx, src/web/screens/home.tsx, src/web/screens/sharingPermissions.tsx
Show both manually added and automatically granted sharing permissions on the dashboard,
=> show automatically granted sharing permissions on dashboard

src/api/configureApi.ts, src/api/helpers/loggingHelpers.ts
=> Reduce header logging.

.gitignore, KeycloakAdvancedSetup.md, README.md, docker-compose.log-stack.yml
Set Grafana to a set version.
Updated Readme to reflect improvement/changes.
=> Setting Grafana version  and minor Readme changes

src/api/configureApi.ts, src/api/entities/AuditTrail.ts, src/api/entities/Participant.ts, src/api/routers/participantsRouter.ts, src/api/services/auditTrailService.ts, src/api/services/participantsService.ts, src/web/components/Input/CheckboxInput.scss, src/web/components/Input/CheckboxInput.stories.tsx, src/web/components/Input/CheckboxInput.tsx, src/web/components/Input/Input.scss, src/web/components/Input/RadioInput.scss, src/web/components/Input/SelectInput.tsx, src/web/components/ParticipantManagement/ApprovedParticipantsTable.stories.tsx, src/web/components/ParticipantManagement/ParticipantApprovalForm.tsx, src/web/components/ParticipantManagement/ParticipantRequestForm.stories.tsx, src/web/components/ParticipantManagement/ParticipantRequestItem.tsx, src/web/components/ParticipantManagement/ParticipantRequestsTable.stories.tsx, src/web/components/ParticipantManagement/ParticipantRequestsTable.tsx, src/web/screens/manageParticipants.tsx, src/web/services/apiRoles.tsx, src/web/services/participant.ts
Added a checkbox selection to choose API roles for user.
Added tooltip option to checkbox
Audit log
=> Add Api Roles Selection to Participant Approval form 

package-lock.json, package.json
=> Updated version

src/api/routers/participantsRouter.ts
respond with a failure when trying to add a duplicate user.
=> error when inviting duplicate user

src/api/entities/AuditTrail.ts, src/api/routers/participantsRouter.ts, src/api/services/adminServiceClient.ts, src/api/services/adminServiceHelpers.ts, src/api/services/apiKeyService.ts, src/api/services/auditTrailService.ts, src/web/components/ApiKeyManagement/KeyEditDialog.spec.tsx, src/web/components/ApiKeyManagement/KeyEditDialog.stories.tsx, src/web/components/ApiKeyManagement/KeyEditDialog.tsx, src/web/components/ApiKeyManagement/KeyEditDialogHelper.spec.tsx, src/web/components/ApiKeyManagement/KeyEditDialogHelper.tsx, src/web/components/ApiKeyManagement/KeyItem.tsx, src/web/components/ApiKeyManagement/KeyTable.stories.tsx, src/web/components/ApiKeyManagement/KeyTable.tsx, src/web/screens/apiKeyManagement.tsx, src/web/services/apiKeyService.tsx, src/web/services/participant.ts
Added action button for API Keys.
Opens dialog which allows API Key name and roles to be edited.
Flow
=> Edit API Key function

src/web/screens/dashboard.tsx
Moved to admin area for temporary while deploying unideal code.
=> Made API Management Page Admin only

src/web/components/ApiKeyManagement/KeyCreationDialog.stories.tsx, src/web/components/Input/CheckboxInput.stories.tsx, src/web/components/Input/CheckboxInput.tsx, src/web/components/KeyPairs/KeyPairDialog.scss, src/web/components/KeyPairs/KeyPairDialog.stories.tsx, src/web/components/KeyPairs/KeyPairDialog.tsx
Removed option for boolean CheckboxInput.
Shifted KeyPair to use `FormStyledCheckbox` instead as was only component using boolean option.
Old
New
=> Removed option for boolean CheckboxInput

src/web/components/ApiKeyManagement/KeyDisableDialog.tsx, src/web/components/ApiKeyManagement/KeyItem.tsx, src/web/components/ApiKeyManagement/KeyTable.stories.tsx, src/web/components/ApiKeyManagement/KeyTable.tsx, src/web/components/Core/Form.tsx, src/web/components/Input/RadioInput.spec.tsx, src/web/screens/apiKeyManagement.tsx, src/web/services/apiKeyService.tsx
Added option on table to disable an API Key. Makes the user type the Key ID before allowing them to disable the key.
=> Add disable API Key option

.github/workflows/release-docker-image.yaml
=> Use kcc branch to increase version number

README.md, src/web/components/ApiKeyManagement/KeyEditDialog.stories.tsx, src/web/components/ApiKeyManagement/keyCreationDialog.spec.tsx, src/web/components/ApiKeyManagement/keyEditDialog.spec.tsx, src/web/components/Input/CheckboxInput.spec.tsx, src/web/components/Input/CheckboxInput.stories.tsx, src/web/components/Input/CheckboxInput.tsx
Added testing for Edit and Create dialogs for API Key Management
=> Key Management UI tests

src/web/components/ApiKeyManagement/KeyCreationDialog.scss, src/web/components/ApiKeyManagement/KeyCreationDialog.tsx, src/web/components/ApiKeyManagement/keyCreationDialog.spec.tsx, src/web/components/Core/CopySecretButton.scss, src/web/components/Core/CopySecretButton.tsx, src/web/components/Core/DisplaySecret.scss, src/web/components/Core/DisplaySecret.stories.tsx, src/web/components/Core/DisplaySecret.tsx, src/web/components/Core/DisplaySecretTable.scss, src/web/components/Core/DisplaySecretTable.stories.tsx, src/web/components/Core/DisplaySecretTable.tsx, src/web/components/KeyPairs/KeyPair.tsx, src/web/configureFontAwesomeLibrary.ts, src/web/styles/themes.scss
Added neater component for key and secret in API Key management.
=> Improving showing secret and key

src/web/components/ApiKeyManagement/ApiRolesCell.scss, src/web/components/ApiKeyManagement/ApiRolesCell.stories.tsx, src/web/components/ApiKeyManagement/ApiRolesCell.tsx, src/web/components/ApiKeyManagement/KeyEditDialog.scss, src/web/components/ApiKeyManagement/KeyEditDialog.tsx, src/web/components/ApiKeyManagement/KeyEditDialogHelper.spec.tsx, src/web/components/ApiKeyManagement/KeyEditDialogHelper.tsx, src/web/components/ApiKeyManagement/KeyItem.tsx
Messages added to table along with when editing key.
=> Added warnings when key has roles participant doesn't have permission for

src/web/components/ApiKeyManagement/KeyEditDialog.tsx, src/web/components/ApiKeyManagement/KeyItem.scss, src/web/components/ApiKeyManagement/KeyItem.tsx
Added styling so edit and disable action icons sit next to eachother.
=> Made API Key actions icons sit next to each other

src/web/components/ClientSideTokenGeneration/CstgDomainInputRow.scss, src/web/styles/tables.scss
Fixed styling issue were inputs were squished when in a table.
=> Fixed input styling within tables

src/web/components/ParticipantManagement/ParticipantManagementItem.scss, src/web/components/ParticipantManagement/ParticipantRequestItem.tsx
=> Added styling to fix approval table

keycloak/themes/uid2-theme/login/resources/css/login.css
**Before**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/bea02d59-26ca-4988-b5b9-d71f2e50363c
**After**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/827c9712-ae48-48af-8968-e5d16837d203
=> Fix styling for password input with invalid login

keycloak/themes/uid2-theme/email/messages/messages_en.properties, src/api/routers/participants/participantsCreation.ts
Change the invitation email to be a bit more descriptive with the new account creation process.
=> update invitation email

src/api/entities/AuditTrail.ts, src/api/entities/Participant.ts, src/api/routers/participants/participantClasses.ts, src/api/routers/participants/participantsCreation.ts, src/api/services/auditTrailService.ts, src/database/migrations/20240326001352_AddCRMAgreementNumberColumnToParticipantsTable.ts, src/database/migrations/20240326001352_AddSalesforceAgreementNumberColumnToParticipantsTable.ts, src/web/components/ParticipantManagement/AddParticipantDialog.tsx, src/web/components/ParticipantManagement/AddParticipantDialogHelper.spec.ts, src/web/components/ParticipantManagement/AddParticipantDialogHelper.ts, src/web/components/ParticipantManagement/ApprovedParticipantItem.tsx, src/web/components/ParticipantManagement/ApprovedParticipantsTable.tsx, src/web/services/participant.ts
- DB Migration to add new column
- Updates to schema to allow the new field to be fetched and updated
- New text field in Add Participant dialog to set the agreement number.
- Display agreement number in approved participants table
- Apply some sonarlint quick fixes
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/71378bfa-0aa0-4afb-9d74-892baf6cc6c1
=> CRM Agreement Number for Participants

src/web/components/ClientSideCompletion/ClientSideCompletion.scss, src/web/components/ClientSideCompletion/ClientSideCompletion.stories.tsx, src/web/components/ClientSideCompletion/ClientSideCompletion.tsx, src/web/components/ClientSideTokenGeneration/CstgDomainsTable.scss, src/web/components/ClientSideTokenGeneration/CstgDomainsTable.tsx, src/web/components/Core/Card.tsx, src/web/components/KeyPairs/KeyPairsTable.scss, src/web/screens/clientSideIntegration.tsx
Add a CSTG completion checker and clean up layout
=> CSTG completion information panel

src/web/screens/dashboard.tsx
=> Move CSTG page to the standard menu.

.trivyignore
New .trivyignore file to address ignoring vulnerabilities during deployment when necessary
=> Add trivyignore file

src/web/components/ApiKeyManagement/KeyCreationDialog.stories.tsx, src/web/components/ApiKeyManagement/KeyDisableDialog.stories.tsx, src/web/components/ApiKeyManagement/KeyEditDialog.stories.tsx, src/web/components/BusinessContacts/BusinessContactDialog.stories.tsx, src/web/components/ClientSideTokenGeneration/CstgAddDomainDialog.spec.tsx, src/web/components/ClientSideTokenGeneration/CstgAddDomainDialog.stories.tsx, src/web/components/ClientSideTokenGeneration/CstgDeleteDomainDialog.stories.tsx, src/web/components/ClientSideTokenGeneration/CstgDomainsTable.stories.tsx, src/web/components/ClientSideTokenGeneration/CstgEditDomainDialog.stories.tsx, src/web/components/KeyPairs/KeyPairDialog.stories.tsx, src/web/components/KeyPairs/KeyPairDisableDialog.stories.tsx, src/web/components/KeyPairs/KeyPairDisableDialog.tsx, src/web/components/KeyPairs/KeyPairEditDialog.stories.tsx, src/web/components/KeyPairs/KeyPairsTable.stories.tsx, src/web/components/ParticipantManagement/EditParticipantDialog.stories.tsx, src/web/components/TeamMember/TeamMemberDialog.stories.tsx
Adjusted the storybook files to use the new pattern so that you can still open and close the dialog, not just see the dialog open all the time.  Every dialog should print something in the console when submitted to verify it worked and submitted the correct information.  Cleaned up reusable code where possible.
=> New dialog pattern part 3 storybook files

src/web/components/ClientSideTokenGeneration/CstgDomainsTable.tsx
bulk delete dialog was not closing
=> fixed bulk delete bug

.vscode/extensions.json, KeycloakAdvancedSetup.md, README.md
- Include instructions to set yourself as an admin user
- Include instructions to assign a site id to your participant
- Add SonarLint as a suggested extension
- Update some of the steps to stand up the UI after several copy changes
=> README improvements

package-lock.json, package.json, src/web/components/Home/DocumentationCard.tsx, src/web/components/Home/SharingPermissionCard.stories.tsx, src/web/components/Home/SharingPermissionCard.tsx, src/web/screens/home.scss, src/web/screens/home.tsx, src/web/services/site.ts, src/web/utils/AwaitTypesafe.tsx
Update Home screen to use loader data and shared loading component.
Minor changes to avoid content reflow on main screen.
Before: 
After:
=> Update Home screen to use loader data and shared loading component.

src/web/App.tsx, src/web/components/Core/PortalHeader.scss, src/web/components/Core/PortalHeader.tsx, src/web/screens/dashboard.tsx, src/web/screens/emailContacts.tsx, src/web/screens/participantInformation.scss, src/web/screens/participantInformation.tsx, src/web/screens/teamMembers.tsx
- Rename Account Information route, components and files
- Comment out dark mode switch
- Hide several links from appearing on dashboard. Instead, show them in the top nav.
- Update styling for portal header dropdown
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/7da58ccd-b2b1-4f04-b6a7-c530e3e31cc8
=> Move several nav routes to top nav menu

.prettierrc, .vscode/settings.json, src/api/routers/participants/participantsCreation.ts, src/api/services/adminServiceClient.ts, src/api/services/participantsService.ts
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/e72f9d44-84d8-4b6d-a21e-94757a8fd20c
=> Update client types when editing participant

README.md, src/api/services/userService.ts, src/web/screens/manageParticipants.tsx, src/web/screens/sharingPermissions.tsx
Warning for publishers without SHARER.
Additional local stack readme instructions for Mac OSX
=> Warning for publishers without SHARER

src/web/components/ClientSideCompletion/ClientSideCompletion.tsx, src/web/screens/clientSideIntegration.tsx
Only show client side completion banner if there are no domain names AND no mobile app IDs
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/86304fce-0fa9-4061-8951-d78af3c90930
=> Client side completion banner for mobile app IDs

src/web/components/Home/RotateApiKeyCard.tsx, src/web/screens/apiKeyManagement.tsx
- Make the button less misleading
- Point to a better docs site
=> Improve UX for API key rotation

src/api/controllers/userController.ts, src/api/routers/participants/participantsCreation.ts, src/api/routers/participants/participantsKeyPairs.spec.ts, src/api/routers/participants/participantsUsers.spec.ts, src/api/tests/businessContactService.spec.ts, src/api/tests/participantsService.spec.ts, src/web/components/ClientSideCompletion/ClientSideCompletion.stories.tsx, src/web/components/ClientSideCompletion/ClientSideCompletion.tsx, src/web/screens/clientSideIntegration.tsx, src/web/services/apiKeyService.ts
- Move away from deprecated methods
- Improve an error message
- Improve some test names
- Remove a use of "as"
- Improve a test assertion
- Fix and improve participant key pairs test
- Fix logic around the CSTG completion banner & added a story
- Other ESLint suggestions
=> Various code improvements

src/web/components/ClientSideTokenGeneration/CstgAddDialog.spec.tsx, src/web/components/ClientSideTokenGeneration/CstgAddDialog.tsx, src/web/components/ClientSideTokenGeneration/CstgTable.tsx, src/web/screens/apiKeyManagement.tsx, src/web/screens/clientSideIntegration.tsx, src/web/services/appIdsService.ts
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/70a75a3f-5944-4219-97ff-ac6a5ecfae51
Similar changes apply to Mobile App IDs.
=> Copy updates for Client Side Integration screen

src/web/App.tsx, src/web/components/Account/CreateAccountForm.tsx, src/web/components/PortalHeader/PortalHeader.tsx
Do not show participant-related nav in the user menu in the registration page.  Also do not show the UI tour.
=> no additional nav in registration page

.eslintrc.js, src/web/components/SiteTour/tourStorage.spec.ts, src/web/components/SiteTour/tourStorage.ts
- Go to the UI and see that the tour is being shown
- If you've previously finished the tour and do not see it, enter the following in the console: delete localStorage['tour-data']
- Finish the tour
- Reload the page and verify that the tour does not show
=> check for new tour versions

src/api/middleware/participantsMiddleware.ts, src/api/middleware/tests/participantsMiddleware.spec.ts, src/api/middleware/tests/usersMiddleware.spec.ts, src/api/middleware/usersMiddleware.ts, src/api/routers/participants/participantsRouter.ts, src/api/routers/usersRouter.ts, src/api/services/participantsService.ts, src/api/services/usersService.ts
Extract middleware from participantsService into participantsMiddleware. Similar for users middleware.
=> Extract middleware from service files

src/web/components/SnailTrail/SnailTrail.scss, src/web/components/SnailTrail/SnailTrail.tsx
Removed the only usage of this component in https://github.com/IABTechLab/uid2-self-serve-portal/pull/501
=> Remove snail trail component

src/web/components/TermsAndConditions/TermsAndConditions.scss, src/web/components/TermsAndConditions/TermsAndConditionsDialog.scss, src/web/components/TermsAndConditions/TermsAndConditionsDialog.tsx, src/web/screens/dashboard.scss, src/web/screens/dashboard.tsx
=> Extract `TermsAndConditionsDialog` component

README.md, package.json, run_portal.ps1
- New powershell script that runs admin and portal in one-go. See README for more details
- Should take about 30s to run, for existing developers (i.e. MSSQL database container is not being created for the first time)
- Succeeds even if the docker images are already running
https://github.com/user-attachments/assets/68cc4641-6d4e-4b66-a5d7-6d05f14ec83e
=> Single command for running portal

Dockerfile_keycloak
- Tested by adding the environment variable to the local docker-compose and saw the detailed logs.
- Can successfully build the Dockerfile_keycloak image successfully
Sources:
- https://www.keycloak.org/server/all-config#category-logging
- https://www.keycloak.org/server/logging
=> Enable debug logging in Keycloak

src/web/components/Input/SelectDropdown.scss
https://github.com/user-attachments/assets/86ed03c5-49b1-4367-afaa-8cc7dabc87ae
=> Select Dropdown dark mode support

src/web/components/Navigation/ParticipantSwitcher.scss
Better design for short/long participant names
https://github.com/user-attachments/assets/f7bcfc4a-61f7-44af-ac3b-ea5c9be6e1e6
https://github.com/user-attachments/assets/2551c0e4-bf0d-4cd1-95ea-0978e6d7f752
=> Participant Switcher UX Improvements

src/web/App.tsx
Only show the UI tour for new users once they have accepted the terms and conditions on a approved participant.
=> Show UI tour at the right time for new users

src/api/routers/participants/participantsApproval.ts, src/api/routers/participants/participantsUsers.ts, src/api/services/usersService.ts, src/web/components/TeamMember/TeamMember.tsx, src/web/components/TeamMember/TeamMembersTable.tsx, src/web/services/domainNamesService.ts, src/web/services/userAccount.ts
=> Display team member user roles

src/web/components/AuditTrail/AuditTrailTable.tsx
=> Audit Trail improve UX when no search result

package-lock.json, package.json, src/web/components/Navigation/SideNav.tsx, src/web/services/auditTrailService.ts
Two copy edits from Gen:
1. Site Id -> Site ID
2. Action: update -> Action: Update 
^ (for all actions)
=> Audit Trail site ID and actions capitalized 

keycloak/realm/realm-export.json
What Changed:
- Add brute force detection to the realm so user gets locked out temporarily if trying too many wrong passwords
- Reduce the number of failures to 10
=> Add brute force detection

docker-compose.yml, sqlServer/entrypoint.sh
- update binary path with new image
- allow initial creation of databases
=> fix initial docker setup

src/api/controllers/userController.ts, src/web/services/userAccount.ts
- disallow removing last team member
=> disallow removing last team member

Dockerfile_keycloak, docker-compose.yml, src/api/services/adminServiceClient.ts
removed the custom welcome theme for keycloak.  it never worked and we don't actually care.
=> Sas UI d2 4130 keycloak error spam

src/api/entities/Participant.ts, src/api/entities/PrimaryContact.ts, src/api/entities/User.ts, src/api/routers/participants/participantsCreation.ts, src/api/services/participantsService.ts, src/web/components/ParticipantManagement/EditParticipantDialog.tsx, src/web/components/ParticipantManagement/EditParticipantDialogHelpers.ts
Insert new entry into primaryContacts db table after creating initial Participant and User
=> Create new primary contacts after adding new participant
