IABTechLab/uid2-self-serve-portal

- Dockerfile_keycloak
- knexfile.ts
- src/api/envars.ts
Enables using k8s secrets for the mssql connections. 
1. Tested locally by building ssportal image and running with `-e SSP_DB_HOST=host.docker.internal -e SSP_DB_PORT=11433`. Checked that api response is returning records after connecting to mssql.
2. Negative test - used wrong values to ensure env is taken properly
3. KK image tested locally by passing env, and checking tables are created in db.
```
docker run --publish 18080:8080 -e KEYCLOAK_ADMIN=.. -e KEYCLOAK_ADMIN_PASSWORD=.. -e KC_DB=mssql -e KC_DB_URL="<jdbcurl>" -e KC_DB_USERNAME=.. -e KC_DB_PASSWORD=..  <imagename>
```
> Kba configure secrets from env

- src/web/axios.ts
- src/web/screens/login.tsx
1. For the front-end, we don't have process.env available. This sets up the api url default that nginx proxy handles later
2. Currently the redirect url is meant for development purposes, and is hard-coded to localhost. Changing this to redirect the user back to the base url. This also makes sure that the front-end doesn't rely on any env variables.
> kba: Use web base url as the redirect url for auth

- Dockerfile_keycloak
- docker-compose.yml
We use realms-export.json for setting up keycloak configurations, but currently it only has development setting by default. 
For integration and prod environments, urls will have to change. To enable this without having to build images that change for each environment, this PR uses ENV variables to modify the realms-export before running the container. 
This ensures we can re-use the same image across environments.
> Enable substituting the localhost values in keycloak docker

- src/web/components/SharingPermission/ParticipantSearchBar.scss
There was a bug in the CSS causing the td padding on the participants search bar to apply to all td elements site-wide. This refactors the file to make better use of SCSS nesting and removes some unnecessary vendor-specific rules.
> Fix participants search bug

- nginx.conf
Currently, the app does not work if the user is on a non-root url and hits refresh. Examples. portal.integ.unifiedid.com/login
This enables the routing using try_files and fixes the order.
> Fix nginx reload for app

- src/api/entities/Approver.ts
- src/api/envars.ts
- src/api/participantsRouter.ts
- src/api/services/approversService.ts
- src/api/services/emailTypes.ts
- src/api/services/nodemailerService.ts
- src/api/services/participantsService.ts
- src/database/migrations/20230621045435_CreateApproversTable.ts
- src/database/seeds/Approvers.ts
ticket: [UID2-1338](https://atlassian.thetradedesk.com/jira/browse/UID2-1338)
Rather than set up a particular email in the env variable to resolve approval requests, this PR introduces a new mapping table that maps the approver with participant types. 
In dev environment,  data seed is required to insert approvers for testing purposes, you can do it by running`npm run knex:seed:run`
Test Screenshot:
> UID2-1338 Send email to TAM based on the participant types

- Dockerfile_keycloak
- docker-compose.yml
- keycloak/themes/uid2-theme/login/login-update-password.ftl
- keycloak/themes/uid2-theme/login/resources/css/login.css
Tweak some CSS and always show "Sign out from other devices" when changing password.
> UID2 1473 Update keycloak

- KeycloakAdvancedSetup.md
- README.md
- keycloak/realm/realm-export.json
- src/api/configureApi.ts
- src/api/usersRouter.ts
- src/web/contexts/ParticipantProvider.tsx
- src/web/services/participant.ts
- Add claimCheck to check if user has api-participant-user role
- Update keycloak to assign api-user by default
- Update bypassHandlerForPaths to be able to check method
- Update getParticipantByUserId to getCurrentUsersParticipant, which use `users/current/participant instead`
Required steps
> UID2-1516 setup role check on endpoint

- src/web/components/Account/CreateAccountForm.tsx
- src/web/components/Core/TermsAndConditions.scss
- src/web/components/Core/TermsAndConditions.stories.tsx
- src/web/components/Core/TermsAndConditions.tsx
- src/web/screens/dashboard.tsx
Even with a very small browser window, the accept button is now available.
> Tweak the t&c dialog CSS to make it work on small-height browser windows.

- package-lock.json
- src/web/components/SharingPermission/BulkAddPermissions.scss
- src/web/components/SharingPermission/BulkAddPermissions.stories.tsx
- src/web/components/SharingPermission/BulkAddPermissions.tsx
- src/web/components/SharingPermission/bulkAddPermissionsHelpers.ts
- src/web/utils/textHelpers.ts
**Build bulk add permissions component.**
This is not fully functional yet (doesn't call any APIs). 
However, it should populate the recommendation message and select default checkboxes based on the recommended types listed in the ticket. Clicking the "View" button will just change the text to "Hide", and vice versa.
Here is a screen recording from storybook (minor css adjustments have been made since):
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/a0b4037d-bb6a-4b1c-9207-d1f57e488f3f
Screenshot with updated padding:
> ajy-UID2-1443-Bulk-add-permissions-component

- keycloak/realm/realm-export.json
- src/api/configureApi.ts
- src/api/envars.ts
- src/api/participantsRouter.ts
- src/api/services/kcUsersService.ts
- src/api/usersRouter.ts
- src/web/screens/dashboard.tsx
> Assign api-partcipant-member when invited user accept T&C

- src/web/components/Core/Collapsible.scss
- src/web/components/Core/Collapsible.stories.tsx
- src/web/components/Core/Collapsible.tsx
Now the whole header is clickable to collapse/expand the Collapsible component. Before, the trigger was just a small box around the chevron icon.
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/aca24764-3842-4558-b6ae-d11b8b27376e
Also, a label string can be passed to the collapsible component:
> ajy-UID2-1443-Collapsible-component-improvements

- src/web/components/BusinessContacts/BusinessContactsTable.scss
- src/web/components/SharingPermission/SharingPermissionsTable.scss
- src/web/components/SharingPermission/SharingPermissionsTable.tsx
- src/web/components/TeamMember/TeamMembersTable.scss
- src/web/screens/manageParticipants.tsx
- src/web/screens/sharingPermissions.scss
- src/web/screens/sharingPermissions.tsx
- src/web/styles/text.scss
- Make the search and add permissions collapsible open by default
- Reduce some gaps between heading details and body 
- Add a gap between sharing permissions heading details and the search and add permissions collapsible
- Reduce font weight of h2 from bold (700) to 600
- Remove border from sharing permissions table
- Align styling of "No Participants" to use h2 and less padding
- Adjust gap between buttons and tables for email contacts and team members
> ajy-UID2-1595-Implement-feedback-regarding-sharing-permissions-page

- src/web/components/Core/TriStateCheckbox.scss
- src/web/components/Core/TriStateCheckbox.stories.tsx
- src/web/components/Core/TriStateCheckbox.tsx
- src/web/components/SharingPermission/ParticipantItem.scss
- src/web/components/SharingPermission/ParticipantItem.stories.tsx
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/components/SharingPermission/ParticipantSearchBar.scss
- src/web/components/SharingPermission/ParticipantsTable.spec.tsx
- src/web/components/SharingPermission/SharingPermissionsTable.scss
- src/web/components/SharingPermission/SharingPermissionsTable.spec.tsx
- src/web/components/SharingPermission/SharingPermissionsTable.tsx
- src/web/styles/tables.scss
- src/web/styles/themes.scss
Making some component changes to prepare for adjusting the delete behaviour depending on the 'addedBy' field. Full functionality is currently blocked since the APIs are not ready.
- Add TriStateCheckbox disabled prop
- Some logic to disable the participant item when addedBy is 'Auto', though it is currently hardcoded to 'Manual' (awaiting APIs)
- Add copy for the delete dialog
- Other styling changes:
- Adjusting the background colour of every second row in the tables
- Fix font weight and line-height within delete dialog
- Fix styling of participants within the search and add dropdown (remove the background)
**TriStateCheckbox storybook**
**Selection enabled for 'Manual' addedBy**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/aeb0f95e-1db3-44a6-9fe4-e749fbb8d55b …
> ajy-UID2-1475-Component-changes-for-adjusting-sharing-delete-behaviour

- src/web/components/Search/SearchBar.tsx
- src/web/components/SharingPermission/ParticipantSearchBar.tsx
Managed to break main (https://github.com/IABTechLab/uid2-self-serve-portal/actions/runs/5922755162/job/16057208608) by having a `SearchBarContainer` that did not provide a `handleOnBlur` method. It probably makes the most sense to set this as optional for now.
In this version, the event listener is added only if `handleOnBlur` is provided and is used as a dependency in the `useEffect` hook. This ensures that the event listener is added and removed properly when `handleOnBlur` changes.
> ajy-UID2-1596-Make-handleOnBlur-optional-in-SearchBar

- src/database/migrations/20230803014224_CreateAuditTrailsTableAndMigrateData.ts
Discovered that this migration will fail if auditTrails is empty, and the error was hard to identify. Was pairing with Lionell at the time - it is a safe change so am just going to merge,
> ajy-Add-condition-to-audit-trail-migration

- src/web/components/SharingPermission/BulkAddPermissions.spec.tsx
- src/web/components/SharingPermission/BulkAddPermissions.stories.tsx
- src/web/components/SharingPermission/BulkAddPermissions.tsx
- src/web/components/SharingPermission/bulkAddPermissionsHelpers.ts
- Populate checkboxes by using the sharedTypes prop, if there are already types that have been shared with
- Render the "View Participants button only when there is a checkbox selected
- Show the warning when unchecking a type that has already been shared with (regardless of what the actual recommendations are)
- Added some tests
- Some refactoring
**Pre-populate checkboxes when the participant has already shared with a type**
**Hide "View Participants" button when there are no checkboxes selected**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/5c6eaa01-004a-46b9-aab4-f86f828f21f2
**Show warning when unchecking a type that has already been shared with**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/7ef4ff49-ee7e-4ef7-87ee-5e1d3520ffed
> ajy-UID2-1617-Bulk-add-component-improvements

- src/web/components/SharingPermission/ParticipantItem.scss
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/components/SharingPermission/ParticipantItemSimple.stories.tsx
* ParticipantItem currently has a checkbox as well as an `addedBy` prop that is not needed in all use cases (e.g. Bulk Add Permissions control). 
* The new ParticipantItemSimple component just has the logo, name and associated types, and ParticipantItem now has a ParticipantItemSimple.
> ajy-UID2-1617-Participant-item-simple

- src/web/components/SharingPermission/BulkAddPermissions.scss
- src/web/components/SharingPermission/BulkAddPermissions.stories.tsx
- src/web/components/SharingPermission/BulkAddPermissions.tsx
- src/web/components/SharingPermission/bulkAddPermissionsHelpers.ts
* Show participants according to checked types
* Show the "View Participants" button when a type is checked
* Some copy changes
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/53754bd1-c519-4abc-bea4-cf42ef9a7801
**Future work**
* Pass the participants into this component, will need to come from the Sites from Admin. We will need to use siteId to map from a SiteDTO to an AvailableParticipantDTO.
> ajy-UID2-List-participants-by-type-in-bulk-add

- src/web/components/Core/SideNav.scss
- src/web/components/Core/SideNav.tsx
- src/web/screens/logout.tsx
- src/web/screens/routeUtils.tsx
Hide the logout link.  The route needs to be rendered for it to work, but we don't want it displayed in the UI.
> hide logout link

- src/api/helpers/siteConvertingHelpers.ts
- src/api/routers/sitesRouter.ts
- src/api/services/participantsService.ts
- src/api/tests/siteConvertingHelpers.spec.ts
Use Participant Name in DB instead of site name
> Use participant name instead of site name

- src/api/routers/sitesRouter.ts
- src/web/components/SharingPermission/BulkAddPermissions.tsx
Use the `completedRecommendations` flag to determine if the current sharing types should be used to populate checkboxes, rather than just checking if there are shared types.
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/6e5b01bb-f51f-4bbf-b697-cf4797e0e5ab
> ajy-UID2-Fix-bulk-add-still-checking-recommended-types

- KeycloakAdvancedSetup.md
- README.md
- keycloak/realm/realm-export.json
Set the secret for `self_serve_portal_apis` in the `realm-export.json` file to match the one that is checked into `main` in the `.env` file. 
- When a dev runs the keycloak setup for the first time, it uses `realm-export.json`, so they will not have to manually generate their own `SSP_KK_SECRET` and set it in their `.env` file
- Existing devs can benefit from this by following the steps below.
**Note: Only do this if you are okay with it removing all your keycloak users.**
1. Ensure you are using the `SSP_KK_SECRET` that is checked into `main`, not your own.
2. Import the keycloak realm by following the instructions in `KeycloakAdvancedSetup.md`. 
3. Go through the account creation & participant approval process in order to sign into the UI
4. Try edit/add/delete users, and it should …
> ajy-UID2-1789-Set-keycloak-secret-in-setup

- src/web/components/Core/Collapsible.scss
- src/web/components/Core/Collapsible.tsx
- src/web/components/Core/Tooltip.scss
- src/web/components/Core/Tooltip.stories.tsx
- src/web/components/Core/Tooltip.tsx
- src/web/components/SharingPermission/BulkAddPermissions.stories.tsx
- src/web/components/SharingPermission/BulkAddPermissions.tsx
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/components/SharingPermission/ParticipantTableHelper.ts
- src/web/screens/accountInformation.scss
- src/web/screens/sharingPermissions.scss
- src/web/screens/sharingPermissions.tsx
- Copy updates for various strings on the sharing permissions screen.
- Add description to individual sharing permissions control
- Change tooltip component with two props: `trigger` and `delayDuration`
- Add tooltip story
- Conditionally show the tooltip on a disabled checkbox in the "Your Sharing Permissions" table
- Styling to the tooltip
- Unrelated changes
- Use children instead of mapping to content in Collapsible component
- Remove unused import
**New tool tip for disabled row & new copy**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/fef1e2df-e541-44e3-9575-f55d6ae0dae3
**Participant Information tooltip working as expected**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/2a8a31eb-0018-4bb5-b86e-16052413baa4
> ajy-UID2-1969-Various-changes-to-sharing-screen

- src/api/services/adminServiceClient.ts
- src/api/services/adminServiceHelpers.ts
- src/web/components/KeyPairs/KeyPairModel.tsx
- src/web/screens/keyPairsScreen.tsx
- src/web/services/keyPairService.tsx
For manual testing with the keypair `name` populated, please check out `ajy-UID2-1929-Add-name-to-client-side-keypair-response` on `uid2-admin`. Otherwise, everything else should work but `name` will be blank.
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/99138dde-e4ac-410b-83e5-d139576e2159
> ajy-UID2-1929-Call-v2-keypairs-endpoint

- src/web/components/SharingPermission/ParticipantItem.scss
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/components/SharingPermission/ParticipantSearchBar.tsx
- src/web/components/SharingPermission/ParticipantTableHelper.ts
- src/web/components/SharingPermission/SharingPermissionsTable.tsx
- Conditionally disable checkbox, including tooltip for disabled state. 
- Ensure consistent styling regardless of the state of checkboxes in the table
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/5e4518f1-de2c-4e53-9108-34c07d61c4fe
> ajy-UID2-Minor-sharing-permissions-fixes

- src/api/routers/usersRouter.ts
- src/web/components/Core/Banner.scss
- src/web/components/Core/Collapsible.scss
- src/web/components/SharingPermission/BulkAddPermissions.scss
- src/web/components/SharingPermission/BulkAddPermissions.tsx
- src/web/components/SharingPermission/SearchAndAddParticipants.scss
- src/web/components/SharingPermission/SearchAndAddParticipants.tsx
- src/web/components/SharingPermission/bulkAddPermissionsHelpers.ts
This includes a minimum-effort change to the usersRouter to populate the current participant with the source-of-truth types, which is used in the participant context in the bulk add control.
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/ab61725a-bca3-4505-b336-a38a65645583
> Warn publishers against removing sharing with DSPs

- src/api/routers/participantsRouter.ts
- src/api/services/adminServiceClient.ts
- src/web/App.scss
- src/web/screens/sharingPermissions.tsx
- src/web/styles/themes.scss
- src/web/utils/apiError.tsx
- Show participant is sharing with DSP when allow_sites is null
- Throw error when sharing participant `/api/sharing/list/` return 404  (**I believe we should hide sharing permission from menu for this case, but I think there is a separate ticket for this already**.)
As discussed, when a participant is GENERATOR or SHARER or has a client_keypair, admin service creates a keyset for it. For now we don't allow user create keyset from portal
- Admin service: [jyg-UID2-1736 return null instead of [] when allow_sites is empty](https://github.com/IABTechLab/uid2-admin/pull/164)
1. Approve participant with a siteId that has SHAERE role, it should get empty allow_sites, and allow_types, it should show recommended bulk permission based on it's clientTypes
2. Approve participant with a siteId with …
> Show participant is sharing with DSP when allow_sites is null

- src/api/routers/participantsRouter.ts
- src/api/services/participantsService.ts
- src/database/migrations/20231024020758_RemoveDeleteCascadeOnParticipantTypes.ts
- Remove on delete CASCADE from participantToTypes and approvers
- Change upsert to use a transaction to update participant  types
> Fix participant types get deleted issue

- src/web/components/SharingPermission/BulkAddPermissions.scss
- src/web/components/SharingPermission/BulkAddPermissions.tsx
- src/web/components/SharingPermission/bulkAddPermissionsHelpers.spec.ts
- src/web/components/SharingPermission/bulkAddPermissionsHelpers.ts
- src/web/services/participant.ts
We had previously implemented this banner once the participant had already completed the recommendations flow, but this PR implements it during the recommendations flow.
I also fixed two bugs which I noticed during development:
**Banner shows at the wrong time**
Before
Note the participant type changes to "DSP" after completing the recommendations. Hence why the warning does not show when unchecking DSP after completing recommendations, because the participant does not appear to be a Publisher.
After
I've also added unit tests for `publisherHasUncheckedDSP`
**Completing the recommendations changes the participant types**
Before
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/2d5e7462-faa2-4632-b12c-35f9277afef1
After …
> Warn Publishers when removing sharing with DSP during recommendations flow

- src/api/routers/sitesRouter.ts
- src/api/services/adminServiceClient.ts
- src/api/services/adminServiceHelpers.ts
- src/api/tests/siteConvertingHelpers.spec.ts
- src/web/components/ParticipantRequests/ParticipantApprovalForm.spec.tsx
- src/web/components/ParticipantRequests/ParticipantRequestForm.stories.tsx
- Create a new method `getVisibleSiteList` in `adminServiceClient.ts` to call `getSiteList()` then filter out the appropriate sites before returning to the front end. 
- The method of filtering allows for existing sites that have `visible==null` to still be included, as that is the default for sites that were created before the `visible` flag was introduced. The default for new sites is `visible==true`
- Use `getVisibleSiteList` in the base (`/`) router and `/available` in the sites router. These routes are only used for non-admin functionality and does not break core functionality of the website when the current participant has a site that has visible set to false
- Ultimately this hides invisible sites from being included on the sharing permissions count on the home screen, as well as …
> Filter out sites from sharing permissions features by using `visible` flag

- src/api/configureApi.ts
- src/api/helpers/loggingHelpers.ts
- src/api/routers/participantsRouter.ts
- src/api/routers/usersRouter.ts
- src/api/services/adminServiceClient.ts
- src/api/services/auditTrailService.ts
- src/api/services/emailService.ts
- src/api/services/participantsService.ts
- src/api/services/sendGridService.ts
- src/api/services/usersService.ts
- Pass traceId from the request through to the service, so that it can be logged
- Refactor the loggers to reduce chance of using the wrong logger (to prevent have cases of `logger.error` instead of `errorLogger.logger`)
- We might have to revisit this design in the future to avoid having to prevent `traceId`s around everywhere, but that will involve a bit more work. Alternative options include using dependency injection or the factory pattern.
**Fail to add a sharing permission**
**Info when sending an email invite**
> Include GUID in existing logging

- DeploymentSteps.md
- src/api/routers/usersRouter.ts
- src/api/services/adminServiceClient.ts
Frontend changes to utilize new admin api call.
Linked to admin pr: https://github.com/IABTechLab/uid2-admin/pull/184
> Utilize new route for admin to just collect 1 site

- src/api/routers/participantsRouter.ts
- src/api/services/participantsService.ts
- src/web/components/ParticipantRequests/ApprovedParticipantItem.tsx
- src/web/components/ParticipantRequests/ApprovedParticipantsTable.stories.tsx
- src/web/components/ParticipantRequests/ApprovedParticipantsTable.tsx
- src/web/components/ParticipantRequests/ParticipantRequestsTable.tsx
- src/web/screens/manageParticipants.tsx
- src/web/services/participant.ts
Added list of Approved Participants to the management screen.
> List participant on management page

- src/web/components/TeamMember/TeamMember.tsx
- src/web/screens/emailContacts.tsx
- src/web/screens/keyPairsScreen.tsx
- src/web/screens/sharingPermissions.tsx
- src/web/screens/teamMembers.tsx
- src/web/utils/apiError.tsx
- Extract `handleErrorPopup` method so that it is no longer defined locally multiple times
- Use `handleErrorPopup` instead of manually setting a message in the frontend - if the messages aren't friendly enough we can just change them on our backend.
- Ensure the `errorHash` is extracted from different error types
- Stronger type safety
> Extract handleErrorPopup method

- src/api/controllers/userController.ts
- src/web/services/userAccount.ts
**Before**
**After**
Also added `return` statements so that we don't get the following api error by setting the status multiple times:
```
Error: Cannot set headers after they are sent to the client
```
> Display errorHash when resending team member invite

- src/api/helpers/siteConvertingHelpers.ts
- src/api/tests/siteConvertingHelpers.spec.ts
Enforce ID_READER AND DSP, rather than ID_READER OR DSP.
Manual Testing
The following site will not show up in sharing permissions:
```
{
"id": 1001,
"name": "Non-DSP with ID_READER",
"clientTypes": [
"PUBLISHER" // Importantly, not DSP.
], 
"roles": [
"ID_READER"
],
},
```
While the following site will show up in sharing permissions:
```
{
"id": 123,
"name": "DSP", // This is mapped to "DSP Example" in the portal db, hence the name in the screenshot below.
"clientTypes": [
"DSP"
],
"roles": [
"ID_READER"
],
},
```
> Stricter check for sharing sites

- src/api/configureApi.ts
The `envars` endpoint was being called before a user had been approved (and therefore received the keycloak role to call our API), so it was failing with `unauthorised`, which would crash the page. 
This PR adds the `envars` endpoint to the list of paths that bypass the claim check, so now it returns with `200` and will not crash the page after a user has verified their email and they are on the `account/create` screen.
> Bypass handler for envar endpoint

- src/api/configureApi.ts
- src/api/entities/ApiRole.ts
- src/database/migrations/20240104050829_DisableOptOutRole.ts
- src/web/screens/manageParticipants.tsx
- src/web/services/apiRoles.tsx
Added migration which adds disabled field to apiRoles in DB. Disabled all keys except for known good keys by default.
DB table
Resulting approval screen
> Hide disabled API roles when selecting roles for participant

- README.md
- package.json
Added the knex down command, which only rolls back the most recent migration instead of the last batch. Should be used in most circumstances.
> Added knex down command

- .github/workflows/build-and-test.yaml
- README.md
- package-lock.json
- package.json
**Node version < 18.18 fails**
```
> nvm use 16.14
Now using node v16.14.2 (64-bit)
> npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: uid2-ssportal@0.10.1
npm ERR! notsup Not compatible with your version of node/npm: uid2-ssportal@0.10.1
npm ERR! notsup Required: {"node":">=18.18"}
npm ERR! notsup Actual:   {"npm":"8.5.0","node":"v16.14.2"}
```
**Node version >=18.18 succeeds**
```
> nvm use 18.18
Now using node v18.18.0 (64-bit)
> npm install
removed 67 packages, and audited 2669 packages in 12s
...
```
> Bump required node version to 18.18

- src/database/migrations/20230201060429_CreateUserTable.ts
- src/database/migrations/20230308044836_UpdateUserSchemeAndAddStatusToParticipant.ts
- src/database/migrations/20231220235718_RemoveParticipantIdColumnFromAuditTrail.ts
- Remove unnecessary console logs
- Replace unused enum with string. Turns out this syntax doesn't work with SQL Server, but it does with SQLite. Our SQL Server db just had `nvarchar(100)` so we've updated the migration to match that.
- Add conditions so that SQL syntax that doesn't work on SQLite shouldn't be run. Specifically, it is not happy with `JSON_MODIFY`
> Clean up DB migration files

- src/api/routers/participantsRouter.ts
- src/api/services/adminServiceClient.ts
Added route for disabling API keys
> Added route to disable API Key

- src/web/components/ApiKeyManagement/KeyDisableDialog.stories.tsx
- src/web/components/ApiKeyManagement/KeyDisableDialog.tsx
Added component to show dialog before disabling API Key. Has not been used in this PR.
> Added disable API Key dialog

- .github/workflows/release-docker-image.yaml
- package.json
- version.json
Remove version.json as it's not relevant for the existing workflow and might introduce inconsistencies in the version number. Bump the version.
> Disable new workflow that isn't working.

- src/api/helpers/siteConvertingHelpers.ts
- src/api/routers/participantsRouter.ts
- src/api/routers/sitesRouter.ts
- src/api/services/adminServiceClient.ts
- src/api/services/adminServiceHelpers.ts
- src/api/tests/siteConvertingHelpers.spec.ts
- src/web/components/ParticipantManagement/ParticipantApprovalForm.spec.tsx
- src/web/components/ParticipantManagement/ParticipantApprovalForm.tsx
- src/web/components/ParticipantManagement/ParticipantRequestForm.stories.tsx
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/screens/manageParticipants.tsx
- src/web/services/site.ts
SiteDTO is only sent to the portal in one place. I am changing the option and as such aim to rename this to a more relevant name
> Rename SiteDTO to SiteAdmin

- src/api/routers/sitesRouter.ts
- src/api/services/adminServiceHelpers.ts
- src/web/components/ParticipantManagement/ParticipantApprovalForm.spec.tsx
- src/web/components/ParticipantManagement/ParticipantApprovalForm.tsx
- src/web/components/ParticipantManagement/ParticipantRequestForm.stories.tsx
- src/web/services/site.ts
When approving a new participant, it will pull apiRoles from the linked site and prefill the form with these roles
> Prefill API Roles when approving a participant

- src/api/services/participantsService.ts
- src/web/components/ApiKeyManagement/KeyItem.tsx
- src/web/components/ApiKeyManagement/KeyTable.tsx
- src/web/components/ParticipantManagement/ParticipantApprovalForm.tsx
- src/web/components/ParticipantManagement/UpdateParticipantDialog.tsx
Added check to endpoint so only adds  enabled api roles when a participant is approved/edited.
Also removed restriction on no API Roles as this provides a way to stop API key management by a participant
> Restrict API Role approval endpoint

- src/web/components/SharingPermission/ParticipantSearchBar.scss
We recently [removed the margin-right at the table level](https://github.com/IABTechLab/uid2-self-serve-portal/pull/319), but we missed adding this one back in.
Before
After
> Fix styling for Add Permissions - Individual

- src/web/components/SharingPermission/ParticipantItem.scss
- src/web/screens/apiKeyManagement.tsx
**Styling for Your Sharing Permissions table**
Before
After
**Toast when deleting a key on API Key Management screen**
Before
After
> Fix styling for Your Sharing Permissions checkbox + copy for keys

- src/web/screens/apiKeyManagement.tsx
Every other outside link (`target='_blank'`) uses this styling except for `DocumentationCard` which uses unique styling.
Before
After
> Fix styling for API Permissions link

- README.md
- src/api/configureApi.ts
- src/api/constant/types.ts
- src/api/controllers/userController.ts
- src/api/helpers/loggingHelpers.ts
- src/api/routers/usersRouter.ts
- src/api/services/loggerService.ts
- Introduce `LoggerService`, which contains a `getLogger` method which accepts a `Request` that extracts the `traceId` which is subsequently used for logging, hence reducing the need to pass around traceIds
- See `resendInvitation()` for an example of the new service in action.
- Decided to create one logger rather than having an `infoLogger` and an `errorLogger` - I think it is simpler without losing anything (unless I am missing something)
> Add LoggerService & inject into UserController

- README.md
- src/api/configureApi.ts
- src/api/tests/utils.ts
**Before**
You have to kill your local API, otherwise you when you run `npm run test-api` you will be hit with:
```
Error: Server is not running.
at Server.close (node:net:2219:12)
at Object.onceWrapper (node:events:632:28)
at Server.emit (node:events:518:28)
at Server.emit (node:domain:488:12)
at emitCloseNT (node:net:2279:8)
at processTicksAndRejections (node:internal/process/task_queues:81:21) {
code: 'ERR_SERVER_NOT_RUNNING'
}
```
**After**
Since the API server runs on a different port, they can both be running at the same time with no issues.
> Run API test server on different port to actual API server

- src/index.tsx
- src/web/Keycloak.ts
- src/web/screens/routeUtils.tsx
Revert some refactoring done as part of https://github.com/IABTechLab/uid2-self-serve-portal/pull/340. It turns out the changes made in the aforementioned PR to [src/testHelpers/testContextProvider.tsx](https://github.com/IABTechLab/uid2-self-serve-portal/pull/340/files#diff-c729b5d173e81313f5856e205131b456893c90b8890546db0c76941d992cfe2a) were sufficient. One the other hand, the changes made to `Keycloak.ts` actually broke functionality. It was over-engineered and went against the intended usage of the package, see https://www.npmjs.com/package/@react-keycloak/web#setup-keycloak-instance
**Before**
Refreshing certain screens (Team Members, Email Contacts, Manage Participants & API Key Management) would lead to errors
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/9d …
> Revert Keycloak.ts refactoring

- Dockerfile_keycloak
- docker-compose.yml
- package-lock.json
- package.json
- Similar to https://github.com/IABTechLab/uid2-self-serve-portal/pull/340 but for `24.0.0`
- `declarative-user-profile` has been deprecated, per https://www.keycloak.org/docs/latest/upgrading/index.html#user-profile-changes
- Run `npm i`
- Re-run docker command to run Keycloak on the updated version
- Run your manual tests, such as logging in, logging out, signing into two different accounts in different sessions, etc.
> Upgrade Keycloak to version 24.0.0

- Dockerfile_keycloak
As part of https://github.com/IABTechLab/uid2-self-serve-portal/pull/343/files I removed `--features=declarative-user-profile` from `docker-compose.yml` but didn't realise I needed to remove it in `Dockerfile_keycloak` as well.
First change `start` to `start-dev` in `Dockerfile_keycloak`
**Before**
```
> docker build -f Dockerfile_keycloak -t ajy-test .
[+] Building 2.5s (9/9) FINISHED
=> [internal] load build definition from Dockerfile_keycloak                                                             1.0s
=> => transferring dockerfile: 774B                                                                                      0.0s
=> [internal] load .dockerignore                                                                                         0.7s
=> => transferring context: 2B …
```
> Remove deprecated feature from `Dockerfile_keycloak`

- src/web/screens/sharingPermissions.tsx
No need for this condition to render the SharingPermissionsTable and no UX changes occur
> Remove condition to render Sharing permissions table

- src/web/App.tsx
**Before**
Note the call to `/envars`
**After**
Note there is no call to `/envars` (temporarily changed condition locally to mimic prod)
> Only call `/envar` endpoint on local dev

- src/web/components/ClientSideTokenGeneration/CstgDomainInputRow.spec.tsx
- src/web/components/Core/Form.spec.tsx
- src/web/components/Core/PortalHeader.spec.tsx
- src/web/components/Input/MultiCheckboxInput.spec.tsx
- src/web/components/Input/RadioInput.spec.tsx
- src/web/components/Input/SelectInput.spec.tsx
- src/web/components/Input/TextInput.spec.tsx
- Ensure all usages of `userEvent` API are awaited
- Use best practice of using `const user = userEvent.setup();` before the component is rendered
- Change some `waitForElementToBeRemoved()` calls to actual assertions.
Source: https://testing-library.com/docs/user-event/intro/
> Ensure `user-event` library is used correctly in react tests

- src/web/components/ParticipantManagement/AddParticipantDialog.scss
- src/web/components/ParticipantManagement/AddParticipantDialog.tsx
- src/web/components/ParticipantManagement/ParticipantRequestForm.stories.tsx
- src/web/components/Search/SearchBar.scss
- src/web/components/Search/SearchBar.tsx
- Create a new search bar component which is form-aware, hence rules (such as required) can be enforced
- Allow search bar results in the **Add Participant Dialog** to display on top of other elements, rather than pushing everything else down
**Before**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/9dabae68-719c-4ce8-8409-dad31c3be7e4
**After**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/28f2674b-c828-4913-a2cd-b74870b49faf
**Fix styling and validation behaviour, per Scott's feedback**
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/6b7e5bdb-691b-4247-a918-ea9c9d05c539
> SearchBarFormInput and styling

- src/web/components/ParticipantManagement/AddParticipantDialog.scss
- Ensure dialog is tall for the given screen. This should reduce the need for the scrollbar (on non-errored state) for most screens
- Make the search results for the site id remain within the dialog. The scrollbar will only appear in the search results when needed.
**Before**
**After**
> Improve scroll behaviour in Add Participant dialog

- src/web/components/ClientSideTokenGeneration/CstgDomain.tsx
- src/web/components/ClientSideTokenGeneration/CstgDomainInputRow.scss
- src/web/components/ClientSideTokenGeneration/CstgDomainInputRow.tsx
- src/web/components/ClientSideTokenGeneration/CstgDomainsTable.scss
- src/web/components/ClientSideTokenGeneration/CstgDomainsTable.tsx
- Styling improvements
- Autofocus input
- Use trash icon instead of "Delete"
- Move "Add" button to the bottom of the table
- Disable the button when the domain is empty
- Update some copy
- Remove unnecessary type assertions
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/8601d6e9-1b63-4347-b657-928628755431
Note: the functionality shown above is not included in this PR.
> UX improvements for Top-Level Domains

- src/web/components/ClientSideTokenGeneration/CstgDomainsTable.tsx
- src/web/components/KeyPairs/KeyPairDisableDialog.tsx
- src/web/components/KeyPairs/KeyPairsTable.tsx
- src/web/screens/clientSideIntegration.tsx
What changed:
- Hyphenated client-side integration where necesary
- Changed certain words to lower case if they are not in the title
- Capitalized ID in Subscription ID
- Changed title to match title in the docs for link to Client Side Integration
> Wording and grammar changes to match docs on client side integration

- src/api/routers/participants/participantsRouter.ts
- src/web/components/KeyPairs/KeyPair.tsx
- src/web/components/KeyPairs/KeyPairDialog.tsx
- src/web/components/KeyPairs/KeyPairEditDialog.tsx
- src/web/components/KeyPairs/KeyPairHelper.ts
- src/web/components/KeyPairs/KeyPairsTable.tsx
- If a key pair name exists and is enabled for a specific site id, do not allow user to create a new key pair with the same name
- When a key pair gets disabled, rename the key pair to [keyPairName]-disabled-[timestamp]
Test Plan:
- Try and create new key pair with same name as one displayed and make sure it does not create the key pair
- Create a new key pair, delete it, then create a new key pair with the same name and make sure the key pair gets created
- Edit a key pair to the same name as another existing key pair and check that it does not allow this
> Unique Key Pair Names per Site

- src/api/services/adminServiceHelpers.ts
- src/web/components/KeyPairs/KeyPairEditDialog.tsx
Show public key and subscription ID in dialog, but as uneditable field.
TextInput disabled is a very light gray, but preferred for now by Kimberly.
> Added public key and subscription id as uneditable fields

- keycloak/realm/realm-export.json
- keycloak/themes/uid2-theme/email/html/executeActions.ftl
- keycloak/themes/uid2-theme/email/messages/messages_en.properties
- Extend "Default Admin-Initiated Action Lifespan" from 12 hours to 7 days
- Display this expiry in the email
- Change "Hey" to "Hi" for all the messages
- Improve some other copy
> Extend keycloak admin action expiry

- src/api/entities/SignedParticipant.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/services/signedParticipantsService.ts
- src/database/migrations/20240430040721_AddSignedParticipantsTable.ts
- src/web/components/SignedParticipants/SignedParticipantsTable.tsx
- src/web/screens/dashboard.tsx
- src/web/screens/signedParticipants.tsx
- src/web/services/participant.ts
- src/web/services/signedParticipant.ts
- New db table with single string column
- New screen that just displays the names of the signed participants in a table
- Fetch data using the usual pattern via the participantsRouter
1. Run the migration: `npm run knex:migrate:latest`
2. Populate the table:
```
select * from dbo.signedParticipants
insert into dbo.signedParticipants (name) values ('Test 3'), ('Test 1'), ('Test 2')
select * from dbo.signedParticipants
```
> Signed Participants screen

- README.md
- src/api/services/participantsService.ts
- src/web/components/ParticipantManagement/AddParticipantDialog.tsx
- src/web/components/ParticipantManagement/AddParticipantDialogHelper.spec.ts
- src/web/components/ParticipantManagement/AddParticipantDialogHelper.ts
- src/web/components/ParticipantManagement/EditParticipantDialog.scss
- src/web/components/ParticipantManagement/EditParticipantDialog.stories.tsx
- src/web/components/ParticipantManagement/EditParticipantDialog.tsx
- src/web/components/ParticipantManagement/EditParticipantDialogHelpers.ts
- src/web/services/participant.ts
- Update service to also return related users
- Add fields to the form, for ease of display and in case we want to allow them to be editable later
- Display the fields
- Extract a helper method - though it's probably more defensive than it needs to be - this case should only happen locally with seed data.
- Fix name of method
- Improve README
https://github.com/IABTechLab/uid2-self-serve-portal/assets/137864392/c1f6a48e-3fba-4f58-99d8-b7ce25885e37
Styling update:
> Show site ID & contact information in Edit Participant dialog

- package-lock.json
- package.json
- src/index.tsx
- src/web/initializeFaro.ts
- Setup Faro using instructions from: https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/quickstart/react/
- This requires setting the `REACT_APP_FARO_URL` variable in your `.env` file - this value can be found in our grafana instance.
- Note: this is currently missing the error boundary setup described here: https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/instrument/faro-react/v6-data-router/#setup-for-react-router-v6-with-a-data-router, as I couldn't get it to work
> Basic Faro setup

- src/web/initializeFaro.ts
- src/web/services/environmentVariables.ts
Add a way to supply client-only settings that don't require an API call.
Supply the faro config this way.
> Update Faro config to be supplied in the client.

- src/api/helpers/errorHelpers.ts
- src/api/routers/participants/participantsDomainNames.ts
- src/api/routers/participants/participantsKeyPairs.spec.ts
- src/api/routers/participants/participantsKeyPairs.ts
- src/api/routers/participants/participantsRouter.ts
- src/web/components/Core/EnvironmentBanner.tsx
- src/web/components/Core/ErrorView.stories.tsx
- src/web/components/Core/ErrorView.tsx
- src/web/contexts/CurrentUserProvider.tsx
- src/web/contexts/ParticipantProvider.tsx
- src/web/screens/home.tsx
- src/web/screens/sharingPermissions.tsx
- src/web/utils/PortalErrorBoundary.test.tsx
- src/web/utils/PortalErrorBoundary.tsx
- src/web/utils/RouteErrorBoundary.tsx
- src/web/utils/apiError.tsx
- src/web/utils/errorHandler.tsx
- src/web/utils/errorHelpers.ts
Some refactoring to support async front-end errors. Notably, renamed our useAsyncError function because the name colided with a framework function and I wanted to avoid confusion.
Introduce an async error pattern for customizing display of errors that occur during route loaders and use this for the home screen.
Full route failure, default behaviour:
Custom async handler (i.e. home.tsx):
> Introduce an async error pattern for customizing loader error display.

- src/api/configureApi.ts
- src/web/components/ClientSideTokenGeneration/CstgAddDomainDialog.spec.tsx
- src/web/components/ClientSideTokenGeneration/CstgAddDomainDialog.stories.tsx
- src/web/components/ClientSideTokenGeneration/CstgAddDomainDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgDomainHelper.spec.ts
- src/web/components/ClientSideTokenGeneration/CstgDomainHelper.ts
- src/web/components/ClientSideTokenGeneration/CstgDomainItem.tsx
- src/web/components/ClientSideTokenGeneration/CstgDomainsTable.stories.tsx
- src/web/components/ClientSideTokenGeneration/CstgDomainsTable.tsx
- src/web/components/ClientSideTokenGeneration/CstgEditDomainDialog.stories.tsx
- src/web/components/ClientSideTokenGeneration/CstgEditDomainDialog.tsx
- src/web/screens/clientSideIntegration.tsx
- src/web/services/domainNamesService.ts
- src/web/utils/textHelpers.ts
What Changed:
- Domain validation all happening on the backend in admin (removed domain validation from front end)
- All types of invalid root-level domains entered will show in both Add Domain dialog and Edit Domain Dialog
- Created an UpdatedDomainResponse type that returns the domains and if they are valid or invalid
- Added removal for '[' and ']' in the trim function
Test Plan:
- Test adding invalid domain with typo (example: test....com)
- Test adding invalid domain that is not valid root-level (examples: blogspot.com, github.io, wmflabs.org)
- Test adding multiple invalid domains 
- Test editing a valid domain to an invalid domain
- Test AddDomainDialog and EditDomainDialog storybook components
> Show all invalid domains in add domains dialog 

- keycloak/themes/uid2-theme/email/messages/messages_en.properties
- src/api/services/kcUsersService.ts
What Changed:
- more clear message when someone receives an email to be added to the portal 
Test Plan:
Test the below actions
What should have the new email subject:
- Add team member
- Resend team member invite
- Add new participant
- Resend participant invite after expiration
What should not have the new email subject:
- Reset password
- Request account
> Improve subject line message for inviting someone to UID2 portal

- src/web/components/SharingPermission/DeletePermissionDialog.tsx
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/components/SharingPermission/ParticipantSearchBar.tsx
- src/web/components/SharingPermission/ParticipantsTable.tsx
- src/web/components/SharingPermission/SharingPermissionsTable.scss
- src/web/components/SharingPermission/SharingPermissionsTable.tsx
What Changed:
- Added  in-line delete button for sharing permissions (also added Actions header)
- Extracted DeletePermissionsDialog to its own file 
Test Plans:
- Add and delete participants in the Sharing Permissions table - both individually and in bulk and make sure everything deletes correctly
> Add in-line delete button to Sharing Permissions Table

- package-lock.json
- package.json
- src/web/components/Home/SharingPermissionCard.scss
- src/web/components/Home/SharingPermissionCard.tsx
- src/web/screens/home.tsx
What Changed:
- banner to show if user does not have sharing permissions on home page (see UX in Jira ticket)
- updated version number for braces npm package - was getting a high vulnerability that was causing the build to fail
Test Plan:
- test that the card looks correct when you do have sharing permissions
- change your participant's site id to a site id that does not have any keysets associated with it in local admin (I changed mine to site id = 1002) and see banner on home page
> Show banner if user does not have sharing permissions

- src/api/routers/participants/participantsKeyPairs.ts
- src/api/services/adminServiceClient.ts
What Changed:
- When participant's site has no keypairs, don't error, but just return empty array instead
Test Plan:
- Test that it works normally when there are keypairs
- Delete all keypairs or change site to site id that has all its keypairs disabled and make sure no error pops up
- Change site id to a site id that has no keypairs (enabled or disabled) and make sure there is no keypair error that pops up
*If interested in replicating the error on main, change siteid to a site that has no keypairs (enabled or disabled), then go to Client-Side Integration page*
> fixed keypair endpoint to return empty array instead of error

- src/web/components/SiteTour/UpdatesTour.tsx
- src/web/components/SiteTour/tourStorage.ts
Temporary solution to the problem - this still needs updates to the pipeline to be complete, but this unblocks release.
> Avoid showing unnecessary tours on each new release.

- src/web/components/ApiKeyManagement/KeyCreationDialog.tsx
- Removed `hideCloseButtons` prop from the create key dialog - this prop is not used anywhere in the code now 
- Added the css for a dialog title for the title of the Create API Key form
> Fix create key dialog for consistency

- src/api/entities/AuditTrail.ts
- src/api/entities/User.ts
- src/api/routers/participants/participantClasses.ts
- src/api/routers/participants/participantsCreation.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/services/auditTrailService.ts
- src/api/services/participantsService.ts
- src/api/services/userService.ts
- src/database/migrations/20240729055559_RenameRoleColumnInUserTable.ts
- src/database/seeds/Users.ts
- src/testHelpers/apiTestHelpers.ts
- src/web/components/Account/CreateAccountForm.tsx
- src/web/components/ParticipantManagement/AddParticipantDialog.scss
- src/web/components/ParticipantManagement/AddParticipantDialog.tsx
- src/web/components/ParticipantManagement/ApprovedParticipantsTable.stories.tsx
- src/web/components/ParticipantManagement/EditParticipantDialog.stories.tsx
- src/web/components/ParticipantManagement/ParticipantApprovalForm.tsx
- src/web/components/ParticipantManagement/ParticipantRequestForm.stories.tsx
- src/web/components/ParticipantManagement/ParticipantRequestItem.tsx
- src/web/components/ParticipantManagement/ParticipantRequestsTable.stories.tsx
- src/web/components/TeamMember/TeamMember.stories.tsx
- src/web/components/TeamMember/TeamMember.tsx
- src/web/components/TeamMember/TeamMemberDialog.stories.tsx
- src/web/components/TeamMember/TeamMemberDialog.tsx
- src/web/components/TeamMember/TeamMembersTable.stories.tsx
- src/web/components/TeamMember/TeamMembersTable.tsx
- src/web/services/participant.ts
- src/web/services/userAccount.ts
- Rename "role" on the Users table to avoid confusion with RBAC. Update usages of entity across services, front end, seed, stories, etc.
- Use the same term we already use in the UI: **jobFunction**
- No functional changes for end user
> Rename "role" to "jobFunction" in User table

- src/database/migrations/20240808041539_PopulateUID2SupportUsers.ts
- Use the existing `dbo.approvers` table to populate the `dbo.userToParticipantRoles` table.
- Since `participantId` is not nullable, it just finds the lowest `participantId` against the existing approver user, then inserts a new row with the `userRoleId` that matches "UID2 Support". This `participantId` here doesn't really matter, since the presence of UID2 Support will bypass any participant restrictions.
- No-op if there are no rows in the approvers table
> Populate support user role for approvers

- src/api/entities/UserRole.ts
- src/api/middleware/participantsMiddleware.ts
- src/api/middleware/tests/participantsMiddleware.spec.ts
- src/api/middleware/tests/usersMiddleware.spec.ts
- src/api/middleware/usersMiddleware.ts
- src/api/routers/participants/participantsCreation.ts
- src/api/services/usersService.ts
- src/database/seeds/Users.ts
- src/testHelpers/apiTestHelpers.ts
- Add checks in the users and participants middleware to check for the existence of the UID2 Support role
- Add a test case to cover the new functionality
- Change from exporting a single user role ID to an enum of all three.
> Check for UID2 Support role in middleware

- src/web/components/ClientSideCompletion/ClientSideCompletion.stories.tsx
- src/web/components/ClientSideCompletion/ClientSideCompletion.tsx
- Address edge case where either domainNames or appIds are all deleted and set to an empty array.
- Add stories to cover edge case.
Before
After
> Ensure client-side completion banner renders appropriately

- src/api/middleware/participantsMiddleware.ts
- src/api/services/usersService.ts
- Remove duplication of user.participants
- Remove duplication of participant.users
1. Set up your user (e.g. abby@example.com) to have multiple userRoleIds for your participant.
1. Call `http://localhost:3000/api/participants/current/users` and look at the response:
```
[
{
"id": 3,
"email": "abby@example.com",
"phone": null,
"participantId": 8,
"firstName": "abby",
"lastName": "example",
"jobFunction": "Marketing",
"acceptedTerms": true,
"deleted": false,
"fullName": "abby example"
},
{
"id": 3,
"email": "abby@example.com",
"phone": null,
"participantId": 8,
"firstName": "abby",
"lastName": "example",
"jobFunction": "Marketing",
"acceptedTerms": true,
"deleted": false,
"fullName": "abby example"
},
{
"id": 5059,
"email": "11077777777777@example.com",
"phone": null,
"participantId": …
```
> Remove duplication from users and participants

- package.json
While working on API changes, the watcher occasionally crashes with:
```
Emitted 'error' event on Server instance at:
at emitErrorNT (node:net:1899:8)
at processTicksAndRejections (node:internal/process/task_queues:82:21) {
code: 'EADDRINUSE',
errno: -4091,
syscall: 'listen',
address: '::',
port: 6540
}
Node.js v20.11.0
[nodemon] app crashed - waiting for file changes before starting...
```
And gets stuck - saving a file just results in the same error. It needs to be manually killed along with the port, then the command needs to be run again to get the local API to work. This commit means that the API-watcher is slightly slower each time but much more reliable.
> Make local API more reliable during development

- src/api/controllers/userController.ts
- src/api/middleware/participantsMiddleware.ts
- src/api/middleware/tests/participantsMiddleware.spec.ts
- src/api/middleware/tests/usersMiddleware.spec.ts
- src/api/middleware/usersMiddleware.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/services/auditTrailService.ts
- src/api/services/userService.ts
- src/web/contexts/ParticipantProvider.tsx
- src/web/screens/apiKeyManagement.tsx
- src/web/screens/clientSideIntegration.tsx
- src/web/screens/emailContacts.tsx
- src/web/screens/homeRedirector.tsx
- src/web/screens/manageParticipants.tsx
- src/web/services/apiKeyService.ts
- src/web/services/appIdsService.ts
- src/web/services/domainNamesService.ts
- src/web/services/keyPairService.ts
- src/web/services/participant.ts
- src/web/services/userAccount.ts
- src/web/utils/loaderHelpers.ts
- src/web/utils/urlHelpers.ts
- General idea: use `useParams()` hook to get `participantId` then populate the ParticipantContext. Then use the ParticipantContext from then on (rather than relying on 'current' or calling `useParams()` from every screen)
- Participant ID is never provided on initial log in, hence why we need to keep the call to `GetUsersDefaultParticipant()`
- Make `participantId` a required parameter where it used to be optional
- Remove support for 'current' in the participant middleware. Refactor to make it more readable. Remove unnecessary tests
- Update some TODOs
1. Change the participantId in the URL to another participant you have access to (i.e. not the first participant for your user in the `usersToParticipantRoles` table). Access comes for free if you have the UID2 Support role:
```
insert …
```
> Always provide participantId in API calls

- src/web/components/ClientSideTokenGeneration/CstgAddDialog.spec.tsx
- src/web/components/ClientSideTokenGeneration/CstgAddDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgHelper.ts
- src/web/components/ClientSideTokenGeneration/CstgTable.tsx
- src/web/components/ParticipantManagement/AddParticipantDialog.tsx
- src/web/components/PortalHeader/PortalHeader.spec.tsx
- src/web/components/PortalHeader/PortalHeader.tsx
- src/web/components/TeamMember/TeamMember.tsx
- src/web/screens/clientSideIntegration.tsx
- src/web/screens/manageParticipants.tsx
- src/web/screens/sharingPermissions.tsx
- Address feedback from Gen/Product
- Remove gravatar icon from profile dropdown & associated test
- Use the correct case regarding the CSTG value types & update tests
- Fix punctuation, pluralisation and upper/lower case in a bunch of other places
- Make the instructions for mobile app IDs clearer
- Add a link to our docs on the sharing permissions page
> Copy changes & remove gravatar

- src/api/controllers/userController.ts
- src/api/routers/participantUsersRouter.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/routers/usersRouter.ts
- src/web/components/TeamMember/TeamMember.tsx
- src/web/components/TeamMember/TeamMembersTable.tsx
- src/web/screens/teamMembers.tsx
- src/web/services/userAccount.ts
- Change a few user routes to be participantUser routes (of the form `/participants/:participantId/users/:userId`). Move these from usersRouter to participantUsersRouter - add this as a subrouter to the participantsRouter. Actual functionality of the endpoints is unchanged
- Pass participantId from front-end using `ParticipantContext`
- Remove an unused function & endpoint
Perform resend invitation or delete/update user and notice the request URL is now of the form `http://localhost:3000/api/participants/8/users/7181` rather than `http://localhost:3000/api/users/7181`
> Move some user routers to participant/user routes

- src/web/components/ClientSideTokenGeneration/CstgAddDialog.spec.tsx
- src/web/components/ClientSideTokenGeneration/CstgAddDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgDeleteDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgEditDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgTable.tsx
- src/web/screens/clientSideIntegration.tsx
- Changed the success toast for CSTG to always use the term "saved", because there's not currently an easy way to tell how many are being added or deleted.
- Removed some unnecessary/inaccurate strings from the tests
- Fixed some more casing issues
- Improved some error messages
https://github.com/user-attachments/assets/bf6bf569-963e-4f74-9c6b-780135298181
https://github.com/user-attachments/assets/6ea439cf-7bab-4b46-af5f-09073ffe6e1a
> Copy changes for root-level domains and mobile app IDs

- src/api/middleware/tests/usersMiddleware.spec.ts
- src/api/middleware/usersMiddleware.ts
- Cover the edge case where the user has access to the requestor participant, but the target user does not belong to that participant
- Make the distinction clearer between the requesting user and the target user (the one that is being changed). Do the same in the tests
- Add a test to cover this case.
> Enhance user middleware to cover edge case

- src/api/controllers/userController.ts
- src/api/entities/AuditTrail.ts
- src/api/routers/participants/participantsAppIds.ts
- src/api/routers/participants/participantsDomainNames.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/services/auditTrailService.ts
- src/api/services/userService.ts
- Support the case where the user is using the portal as a participant that is not their default participant for audit trails and `acceptTerms()`
- For auditing, use the actual `participantId` that is specified, rather than just defaulting to the first one for the user.
- For `acceptTerms()`, check if the user belongs to any approved participant, rather than just checking if their first participant has been approved.
> Stop defaulting to first participant for auditing and `acceptTerms()`

- src/web/App.tsx
- src/web/components/PortalHeader/PortalHeader.tsx
Use the existing `acceptedTerms` boolean on the User to determine:
- If we direct from successful login to the home page (this was causing an infinite redirect loop on `main`)
- If we show the UI tour
- If we show the participant routes (Participant Information, Team Members & Email Contacts)
https://github.com/user-attachments/assets/3e170985-0538-408c-b422-4934f95993bb
https://github.com/user-attachments/assets/04753103-5a3b-4911-9d9b-867bc729161e
> Improve UX for user who has not accepted terms

- src/web/services/participant.ts
Match property names in `AddParticipantForm` to the input names in `AddParticipantDialog`. This mismatch prevented defaults to be set on the contact inputs, which was slowing down developer iteration.
**Still working like normal**
https://github.com/user-attachments/assets/6d6e57e6-86df-40fe-bc63-91719811024f
**With a default value set**
```
const formMethods = useForm<AddParticipantForm>({
defaultValues: { siteIdType: 0, firstName: 'hello reviewer' },
});
```
https://github.com/user-attachments/assets/7c86ef32-2a6f-40e6-98a2-cbc2114f2c43
> Align property names in `AddParticipantForm`

- src/api/configureApi.ts
- src/api/controllers/userController.ts
- src/api/routers/participants/participantsCreation.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/routers/participants/participantsUsers.ts
- src/api/services/kcUsersService.ts
- src/web/stores/userStore.ts
https://github.com/IABTechLab/uid2-self-serve-portal/pull/516 will be changing the functionality to allow user invitations to still work when the user already belongs to another participant. I'm doing this refactoring to make it easier for me to add that functionality as well as make it easier to be reviewed. 
- There are no functional changes.
- Rename a function to avoid confusion with an upcoming function to send an invite to an existing user
- Split out the handler for inviting a new participant/user to `participantsUsers.ts`
- Extract a method out of the handler for creating a new participant. This started as more of an exercise but figured it was still worth merging.
- Wrapper method to assign keycloak user role. It's the only role we use today anyway.
- Remove an unused file
> Refactor some user invite code

- emailTemplates/inviteExistingUserToParticipant.hbs
- src/api/routers/participants/participantsCreation.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/routers/participants/participantsUsers.ts
- src/api/services/usersService.ts
- Allow for existing user to be added to a brand new participant
- Allow for existing user to be added to an existing participant
- New email template for existing user being invited
https://github.com/user-attachments/assets/ebeaeb42-7b77-4a35-bb62-8a642d25d4b2
https://github.com/user-attachments/assets/aff9b542-1678-432d-a6ad-b79ec1db8654
Support user deletion in the multiple-participant access world.
> Support user invites for multiple participants

- CodingStandards.md
- src/api/controllers/userController.ts
- src/api/middleware/participantsMiddleware.ts
- src/api/middleware/usersMiddleware.ts
- src/api/routers/participants/participantsAppIds.ts
- src/api/routers/participants/participantsDomainNames.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/routers/participants/participantsUsers.ts
- src/api/services/businessContactsService.ts
- src/api/services/participantsService.ts
- src/api/services/userService.ts
Actioning feedback originally raised [here](https://github.com/IABTechLab/uid2-self-serve-portal/pull/516#discussion_r1742651141)
The convention here is to use PascalCase should be used for models or types that are intended to be reused across the application, while camelCase should be used for schemas that are defined within a specific, narrow scope, like a single function. 
Also we should refer to these zod objects as schemas, rather than parsers, which seems to follow convention (e.g. [zod docs](https://zod.dev/?id=basic-usage), [aws docs](https://docs.powertools.aws.dev/lambda/typescript/latest/utilities/parser/#key-features).
> Consistent naming for zod object variables

- src/web/components/Core/ErrorView/ErrorView.scss
- src/web/components/Core/ErrorView/ErrorView.tsx
- src/web/utils/errorHandler.tsx
- Move the file to a better location
- Leverage scss to simplify
- align center instead of flex-start
UX should remain unchanged, e.g. set your clientTypes to `[]` in admin and the you'll see the following:
> `ErrorView` styling adjustments

- .trivyignore
- src/api/middleware/participantsMiddleware.ts
- src/api/middleware/tests/participantsMiddleware.spec.ts
- src/api/middleware/usersMiddleware.ts
If a user tried to access a participant that they did not have access to, our API would error with `Error: Cannot set headers after they are sent to the client`.
In the above scenario, the API now appropriately responds with 403 or 404
> Ensure response status is only set once

- docker-compose.yml
- src/api/middleware/metrics.ts
- Set up a proper dependency for keycloak on the db, so that keycloak only starts when the db is definitely up. It will make it slightly slower to start up but will be more reliable.
- Filter out paths with whitespace for metrics, to stop the API from logging the following error: `unable to capture route for prom-metrics: Error: argument must not contain whitespace`
1. Run `./run_portal.ps1
2. Notice that the keycloak container only starts when the database is healthy.
https://github.com/user-attachments/assets/b79a2aff-bfef-44bc-998d-1a8757573db1
> Developer experience improvements

- src/api/services/userService.ts
- src/api/services/usersService.ts
- src/testHelpers/dataMocks.ts
- src/testHelpers/testContextProvider.tsx
- src/web/components/Input/SelectDropdown.scss
- src/web/components/Navigation/ParticipantSwitcher.scss
- src/web/components/Navigation/ParticipantSwitcher.spec.tsx
- src/web/components/Navigation/ParticipantSwitcher.tsx
- src/web/components/Navigation/SideNav.tsx
- src/web/contexts/CurrentUserProvider.tsx
- src/web/contexts/ParticipantProvider.tsx
- src/web/utils/urlHelpers.ts
- Update user service so that if user is UID2 support, then populate their participants with all approved participants
- New Participant Switcher UI component, largely driven off react context (rather than prop-drilling). Renders a dropdown if the user has access to multiple participants, otherwise it just displays the user's current participant name. Add this switcher to the side nav.
- First example of testing while mocking user and/or participant context. Expanded the existing `TestContextProvider` so one can optionally provide participant and user context values.
https://github.com/user-attachments/assets/8eb9bc3e-bcd3-4136-b4ba-203520986e0d
https://github.com/user-attachments/assets/328b9d6c-edac-4d1c-9c33-99023b76a9ea
UX improvements like search in the dropdown
> Participant Switcher UI

- src/api/routers/participants/participantsApiKeys.ts
- src/api/routers/participants/participantsAppIds.ts
- src/api/routers/participants/participantsApproval.ts
- src/api/routers/participants/participantsCreation.ts
- src/api/routers/participants/participantsDomainNames.ts
- src/api/routers/participants/participantsKeyPairs.spec.ts
- src/api/routers/participants/participantsKeyPairs.ts
- src/api/routers/participants/participantsRouter.ts
- src/api/routers/participants/participantsSharingPermissions.ts
- src/api/routers/participants/participantsSigned.ts
- src/api/routers/participants/participantsUsers.spec.ts
- src/api/routers/participants/participantsUsers.ts
- src/api/services/participantsService.ts
- src/web/components/ParticipantManagement/ParticipantApprovalForm.tsx
- src/web/components/ParticipantManagement/ParticipantRequestItem.tsx
- src/web/components/ParticipantManagement/ParticipantRequestsTable.tsx
- src/web/services/participant.ts
- Split up the `participantsRouter.ts` file based on domain/feature
- Logically group the routes, ensuring the correct middleware still gets run
- Refactoring only - no functional changes
- We are about to change how permissions work, so this makes it easier to make those changes. i.e. it is easier to identify which middleware needs run against certain endpoints.
> Split up `participantsRouter` file

- src/web/components/ApiKeyManagement/ApiRolesCell.scss
- src/web/components/ApiKeyManagement/ApiRolesCell.tsx
- src/web/components/Core/ErrorView/ErrorView.stories.tsx
- src/web/components/Core/Labels/Label.scss
- src/web/components/Core/Labels/Label.stories.tsx
- src/web/components/Core/Labels/Label.tsx
- src/web/components/Core/Labels/LabelRow.scss
- src/web/components/Core/Labels/LabelRow.stories.tsx
- src/web/components/Core/Labels/LabelRow.tsx
- src/web/components/ParticipantManagement/ApprovedParticipantItem.tsx
- src/web/components/ParticipantManagement/ParticipantManagementItem.scss
- src/web/components/ParticipantManagement/ParticipantRequestItem.tsx
- src/web/components/SharingPermission/ParticipantItem.scss
- src/web/components/SharingPermission/ParticipantItem.tsx
- src/web/components/TeamMember/TeamMember.tsx
- src/web/components/TeamMember/TeamMembersTable.scss
- We will soon be adding labels to show what roles each user has for the current participant. 
- We currently have labels in numerous places throughout the UI, but they each backed by divs with bespoke class names and styling.
- Now is a good time to consolidate these into a component, to allow for better re-usability.
- Introduce `<Label>` and `<LabelRow>` components
- Use them instead of divs for API roles, Participant Types and Team Member (Pending) labels.
- Made the styling more uniform - i.e. increased the font size of the participant type labels to align with the others.
> Label components

- src/api/middleware/participantsMiddleware.ts
- src/web/App.tsx
- src/web/components/Navigation/ParticipantSwitcher.tsx
- src/web/components/PortalHeader/PortalHeader.tsx
What Changed:
1. Added a localStorage variable for the last selected participant id 
2. If there is no last selected participant id, it will just default to the participant id of the user logged in
3. Added a localStorage variable for the last selected dark mode setting
Test Plan:
Last selected partcipant id:
1. Log in and see that the selected participant is your participant 
2. Select another participant and make sure everything changes smooth (remember which participant you selected)
3. Log out
4. Log back in and confirm that the selected participant is the one you last chose
Last selected dark mode:
1. Log in and change the dark mode setting
2. Log out, log back in and confirm the dark mode setting is the one you had before logging out
3. Test for both light mode and dark mode
> Local storage added to save most recent selected participant and dark mode setting

- src/web/components/AuditTrail/AuditTrail.scss
- src/web/components/AuditTrail/AuditTrailTable.tsx
- Remove the left-right padding on contents of the table
- Ensure the paging tool renders as long as there are rows to display. This addresses an edge case where:
- the number of audit rows is between 50 and 100
- the user selects the 100 rows per page option
- the paging tool disappears
> Audit trail table improvements

- run_portal.ps1
- Stop all java processes before starting a new one, to prevent running multiple `OpenJDK Platform binary` processes:
> Improve run_portal command

- src/api/controllers/userController.ts
- src/api/entities/UserRole.ts
- src/api/routers/participants/participantsUsers.ts
- src/api/services/userService.ts
- src/api/services/usersService.ts
- src/web/components/Input/RadioInput.scss
- src/web/components/TeamMember/TeamMember.tsx
- src/web/components/TeamMember/TeamMemberDialog.tsx
- src/web/components/TeamMember/TeamMembersTable.tsx
- src/web/services/userAccount.ts
- Ability to assign Admin or Operations role to users on the **Team Members** screen
- Prevent user from self-unassigning Admin role
- Improve style file
https://github.com/user-attachments/assets/6a59ee06-16a7-4305-987a-a53dd2f78a4f
https://github.com/user-attachments/assets/dfc50e48-2ff8-4d8f-9cd0-3a1cfd5d29fb
Currently just shows the IDs, but I think we will display the actual user role names in a separate ticket
https://github.com/user-attachments/assets/770e148c-69d9-4739-92a2-6a302e83230e
> Team Members User Role Management UI

- src/api/routers/participants/participants.ts
- src/api/routers/participants/participantsApiRoles.ts
- src/api/routers/participants/participantsRouter.ts
> Extract participant handlers to separate file

- src/api/routers/participants/participantsRouter.ts
Ensure that the participant on the request still gets enriched, so that it does not result in 401 error
https://github.com/user-attachments/assets/f6891503-ea32-4ed6-bd64-e2654f131c94
> Prevent uid2 support routes from always 401ing

- src/api/entities/AuditTrail.ts
- src/api/entities/UserRole.ts
- src/api/routers/participants/participantsApiKeys.ts
- src/api/routers/participants/participantsApproval.ts
- src/api/routers/participants/participantsCreation.ts
- src/api/routers/participants/participantsUsers.ts
- src/api/services/participantsService.ts
- src/api/services/userService.ts
- src/database/migrations/20241024212425_ImproveAuditTrailEfficiency.ts
- src/web/components/AuditTrail/AuditTrailRow.tsx
- src/web/components/AuditTrail/AuditTrailTable.tsx
names rather than ids in audit trail.  index on participantId in audit table.
This helps the audit trail to be more human-readble.
> names rather than ids in audit trail.  index on participantId in audit table

- src/web/App.tsx
- src/web/components/Navigation/NoParticipantAccessView.tsx
Quick bug fix to show something different than the Participant Switcher if the user navigates to a participant they don't have access to, but only belong to one participant.
Test Plan:
- Make sure navigation with the switcher still works when a user has multiple participans
- Update your user to only have access to one participant and check the UX when navigating to a participant in the URL that doesn't exist or they don't have access to (example: http://localhost:3000/participant/123333/home)
> Fix participant no access when single participant

- src/web/components/SiteTour/tourHelpers.spec.ts
- src/web/components/SiteTour/tourStorage.spec.ts
- src/web/components/SiteTour/tourStorage.ts
What Changed:
- Added a check for local storage to see if user has nothing in their local storage, then do not show the UI tour since they will be a new user and everything is new to them 
*Note: this check relies on local storage, meaning if a user logs in on a different device or happens to clear their local storage, they would not see the tour steps, but I think it's safe to assume the case is rare where they would log in on a different device or clear their local storage and be needing to see new features for the first time*
Test Plan:
- Create an account and log in as that user for the first time (make sure there is nothing in local storage for tour data from your normal user)
- Make sure you don't see the UI tour
> Do not show UI tour with updates for new users

- src/api/services/participantsService.ts
- src/web/components/ApiKeyManagement/KeyCreationDialog.tsx
- src/web/components/Core/Tooltip/Tooltip.tsx
- src/web/components/KeyPairs/KeyPairsTable.scss
- src/web/components/KeyPairs/KeyPairsTable.tsx
- src/web/screens/apiKeyManagement.tsx
- src/web/screens/clientSideIntegration.tsx
What Changed:
- Added definitions in info tooltip for key pairs, subscription id, public key
- Improve message when creating an API key so the user is aware the key needs to be kept secret
- Make it clear that API keys are for client-server and server-side
- Reference CSTG in API keys and vice versa
> Add more descriptions to api key and cstg pages to differentiate them

- src/api/services/adminServiceClient.ts
What Changed:
- Removed the two instances of specifying validateStatus that match the default, so they are not necessary ( >= 200 && <= 300)
Test Plan:
- This only happens in two functions related to sharing.  Test that sharing still works fine in the portal
> removed the default validate status instances

- .vscode/settings.json
- src/api/controllers/userController.ts
- src/web/components/Home/RotateApiKeyCard.stories.tsx
- src/web/components/ParticipantManagement/ParticipantManagementItem.tsx
- src/web/components/ParticipantManagement/ParticipantManagementTable.tsx
- changed spelling errors to hints
- fixed the one actual problem
-  exhaustively opened all files to check for problems (the file has to be open in the editor)
> clean up problems tab in vs code

- src/api/entities/AuditTrail.ts
- src/api/entities/User.ts
- src/api/middleware/usersMiddleware.ts
- src/api/routers/managementRouter.ts
- src/api/services/managementService.ts
- src/api/services/userService.ts
- src/api/services/usersService.ts
- src/database/migrations/20250304185826_lock-column-users-table.ts
- src/web/App.tsx
- src/web/components/Navigation/LockedUserView.scss
- src/web/components/Navigation/LockedUserView.tsx
- src/web/components/PortalHeader/PortalHeader.scss
- src/web/components/UserManagement/UserManagementItem.scss
- src/web/components/UserManagement/UserManagementItem.tsx
- src/web/components/UserManagement/UserManagementTable.tsx
- src/web/contexts/CurrentUserProvider.tsx
- src/web/screens/manageUsers.tsx
- src/web/services/userAccount.ts
- migration added for locked row on user table.  Run `npm run knex:migrate:latest`
- disallow access to locked users
- allow superusers to lock user from the user management page
- do not return locked users in queries outside of the user management page.
https://github.com/user-attachments/assets/a8e054ec-f36f-44fc-a5ed-dd4e93e8b2d0
> allow locking users

- src/api/services/usersService.ts
What Changed:
- Add api-participant-member role to user if they already exist but did not belong to any participants 
Test Plan:
- Delete a team member from their only participant.  Check that user in your local Keycloak console and observe that the role is not in the list of roles and that logging in as that user does not access the portal.  Then add the team member back to a participant and check that the role was added back and the user once again has portal access.
> Fix add api-participant-member role when readding user

- src/api/services/adminServiceClient.ts
Make sure Api Keys that include '+' are translated correctly when making api calls
> Delete api keys with plus sign

- src/web/components/ClientSideTokenGeneration/CstgAddDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgEditDialog.tsx
- src/web/components/ClientSideTokenGeneration/CstgHelper.ts
Previously, multi-tenant domains (i.e., .vercel.app, .github.io) failed to pass validation because our exctraction logic didn't account for private suffixes which has to be explicitly required.
> Fix domain extraction to allow multi-tenant domain names to be passed
